### ISSUE TITLE
Node port number has a constructor in the number field during LiveView

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/cardano-node#1025]
**Summary**
Node port number has the constructor "Just" in the number field using LiveView

**Steps to reproduce**
1. Perform pioneer exercise 3
2. Install Cardano Node 1.12.0
3. Launch Node in LiveView

**Expected behavior**
Should only contain the port number

**System info (please complete the following information):**
- OS: Ubuntu
- Version: 20.04
- Node version: 1.12.0

**Screenshots and attachments**

![photo_2020-05-22_22-13-49](https://user-images.githubusercontent.com/25856278/82719615-3e192580-9c7a-11ea-8b91-b7e791a5acdb.jpg)
![photo_2020-05-22_21-46-31](https://user-images.githubusercontent.com/25856278/82719617-407b7f80-9c7a-11ea-8b5f-c48a6a40492d.jpg)

**Comment by erikd** [comment]
I see this same issue building for and running on mainnet.

**Comment by dcoutts** [comment]
The question here is what we want, and is it important. The port number is just one bit of info, and currently it will be wrong for some configurations.

The general info is the addresses (yes, plural) that the node is listening on for remote connections. So that's a _list of IP addresses_ on local interfaces, with corresponding port numbers. Some of those will be IPv6 so the addresses can be huge.

And currently this info will be missing/wrong if the node is configured to use systemd socket activation. The live view currently takes its port number from the CLI. But this is wrong. It misses out if it get specified in the config file and it misses the case of systemd socket activation, where we get passed pre-created sockets rather than creating them ourselves.

So what do we actually want?

**Comment by intricate** [comment]
I believe this was addressed by https://github.com/input-output-hk/cardano-node/pull/1076
