### ISSUE TITLE
Trace failure to create block when it is our turn

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-node#1090]
https://github.com/input-output-hk/ouroboros-network/pull/2169
adds a new more specific tracer value:
```
  -- | We did the leadership check and concluded that we should lead, but cannot
  --
  -- This should only happen rarely and should be logged with warning severity.
  --
  -- Records why we cannot lead.
  | TraceNotCannotLead SlotNo (CannotLead (BlockProtocol blk))
```
We should indeed log this, probably at `Error` or `Critical` severity.

**Comment by edsko** [comment]
This issue is closed, but right now this feature is not actually used yet. Some additional instances will be required of Byron after https://github.com/input-output-hk/ouroboros-network/issues/2172 / https://github.com/input-output-hk/ouroboros-network/pull/2176 is done, and similarly for Shelley when https://github.com/input-output-hk/ouroboros-network/issues/2171 is done.
