### ISSUE TITLE
[FR] - LiveView and cli query tip should include current epoch / slot information

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/cardano-node#1195]
Currently the sample output of querying the tip information outputs:

Tip (SlotNo {unSlotNo = 32032}) (ShelleyHash {unShelleyHash = HashHeader {unHashHeader = f14ed0605fa5cc0ada0c0445a1948e9682cf85b0d9e63860e2a803aa433e5af6}}) (BlockNo {unBlockNo = 8248})

it would be useful for pool operators to have a new field that would show current epoch / slot within the epoch, to save us needing to do the querying of genesis settings and doing modulo arithmetic. 

Similarly, LiveView could be enhanced to add a field to show current network clock (epoch / slot no), so to speak - this would make it easier to detect whether the last time node fetched some new block information from the network was a long time ago (e.g. indicating stuck network / stuck node).

**Comment by vix-io** [comment]
Hi bergr01, this is Viktor at IOHK Tech Support. Thank you for submitting this feature request. We have added it to our backlog and we`ll allocate it to one of our future development sprints. We appreciate your participation and support for the Cardano project!

**Comment by denisshevchenko** [comment]
Since `LiveView` is officially deprecated and will be removed from the node very soon, I'm closing this issue. Please check [RTView](https://github.com/input-output-hk/cardano-rt-view/), our new tool for real-time watching for Cardano nodes. You can open an issue [here](https://github.com/input-output-hk/cardano-rt-view/issues/).
