### ISSUE TITLE
[FR] - High Availability

### ISSUE THREAD

**Issue by tstdin** [input-output-hk/cardano-node#1273]
**Exernal**

**Describe the feature you'd like**
At the moment, cardano-node does not support pool operators in running the node with high availability. And even by design there are forced shutdown periods - e.g. KES rotation requires node restart. In addition to the forced shutdowns, it is possible that the Internet connectivity will go down for a short while, or power outage will occur.

There are several alternatives how to make pool operators lives easier:

1. Implement HA support directly inside cardano-node, so the topology of e.g. 3 relays + 2 block producing nodes would be able to correctly make blocks only from 1 BP node and if one of them goes offline, the other will handle the block production.
2. Add CLI commands to promote/demote relay nodes into block producing. Example: 3 relays publicly accessible from outside and 1 relay + 1BP only connected through the local network. If the BP goes down, we (or script) could promote the relay into BP node.
3. Make the BP node start *really fast*, so when one location goes offline, we can quickly replace it by another.
4. There are probably other ways I did not think of...

At the moment I am considering to run my stake pool in Kubernetes multi-master cluster. However, the software does not give me a slightest chance to prevent downtime.

**Describe alternatives you've considered**
related to #1027

**Additional context / screenshots**
n/a

**Comment by zenithpool** [comment]
It would be best to implement this outside of the cardano-node. 

To run a HA relay nodes, you can run multiple relays behind a proxy or a load balancer already with no problem today. This is already native in Kubernetes and is simple.

If you want to run multiple core/block-producer nodes it gets a little more complicated. You can only have one BP node that your relays are talking to. But you want to have standby BP nodes so that you can rotate KES keys or in an event of a failure. The best way to deploy your BP is to deploy it in an active-passive architecture. To do this in Kubernetes it gets complicated but you can use a combination of a Statefulset, readiness/liveness probes and this active-passive controller in order to achieve this (https://github.com/andreykaipov/active-standby-controller). This will have it so that you only have your relays communicate to only one BP node at a time in order to not cause forks. You can then do the rollout deployments to make changes to your BP nodes and without little to no loss of service.

**Comment by tstdin** [comment]
Thanks @zenithpool for your ideas.

The relay nodes are fairly simple, as you said. The core node is what is problematic. I was aiming for the active-passive architecture. However, I don't see at the moment how you could run a passive core node in a way, that it would be syncing with other nodes (getting latest blocks to be on the tip when the time comes), but also not producing a block when your pool is elected to create one. Not even with the active-standby-controller you shared, if I understand correctly what it does.

On the ITN with Jormungandr, it was much easier, because there were those promote/demote commands. I can imagine something similar being implemented also for the cardano-node as a simple bool switch -> you can create blocks / you can't create blocks.

**Comment by ThaiTheo** [comment]
You can already create a HA bp node in an active-passive mode. The bp node stays current by pulling data from the relays. The minted block on the bp node gets onto the block-chain because it is pulled away by the relays. So if your passive bp node doesn't allow incoming traffic on the port that cardano-node is running, it might be signing blocks but those blocks don't ever reach the network. When your active bp node goes down for whatever reason, make sure incoming traffic on the cardano-node port gets blocked. After that enable incoming traffic to the cardano-node port on the passive bp node. Now your previously active bp node has become passive and your previously passive bp node has become active. There is no need btw to put relay nodes behind load balancers, because with the topology.json file you can create your own hub and spoke model where all relays are treated as separate hubs. If you are using a cloud provider then use the machine's own firewall to allow or block incoming traffic because that is instantly, where cloud based firewalls need some time to become active.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please re-open.
