### ISSUE TITLE
[BUG] - ledger-state dumps cbor

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#1333]
**Internal**

**Summary**
`ledger-state` command returns raw CBOR with an error `Verion mismatch beteen node and consensus, so dumping this as generic CBOR.`

**Steps to reproduce**
`cardano-cli shelley query ledger-state --testnet-magic 42`

**Expected behavior**
dumps json representation of ledger state.

**System info (please complete the following information):**
1.14.0

**Screenshots and attachments**
- If applicable, add screenshots, config files and/or logs to help explain the problem.

**Additional context**

**Comment by mrBliss** [comment]
Per @JaredCorduan's request, the query now returns an `EpochState` instead of a `LedgerState` (https://github.com/input-output-hk/ouroboros-network/commit/60ff736382948c4eee7c263609878209621e6831), this change hasn't been reflected in this repository. Relevant lines: https://github.com/input-output-hk/cardano-node/blob/f12dd511db2479c192a7666675fdcab0374b79e4/cardano-api/src/Cardano/Api/LocalStateQuery.hs#L211
