### ISSUE TITLE
I run the node. Can I communicate directly with the node without the rpc interface?

### ISSUE THREAD

**Issue by wshhz** [input-output-hk/cardano-node#1374]
I just want to run a node to join the network, and then communicate with the node through the rpc interface to complete the operations of obtaining block information and sending transactions. How should I build the node?

**Comment by kevinhammond** [comment]
Follow the instructions in https://github.com/input-output-hk/cardano-tutorials/tree/master/node-setup
and the exercises in https://github.com/input-output-hk/cardano-tutorials/tree/master/Shelley-testnet

You will need to use the cardano-cli interface to communicate with the node.

**Comment by wshhz** [comment]
Why not let node directly provide all rpc interfaces?

**Comment by dcoutts** [comment]
The node does have a low level IPC interface. If you don't mind writing code you can use that directly. Otherwise, use the APIs and CLIs provided.

https://input-output-hk.github.io/ouroboros-network/ouroboros-network/Ouroboros-Network-Protocol-ChainSync-Client.html

https://input-output-hk.github.io/ouroboros-network/ouroboros-network/Ouroboros-Network-Protocol-LocalTxSubmission-Client.html

**Comment by sobitada** [comment]
We aim to start working on a cardano-library and client for the cardano-node in Go.

One of the basic functionality would be to build, sign and send transactions to the cardano-node. However, we don't want to embed the cardano-cli. Is there a languages-agnostic protocol to communicate over the socket?

**Comment by liuxh-go** [comment]
@sobitada Hello, have you started to make cardano-library in go language?
