### ISSUE TITLE
[BUG] - Some blocks generated with size over validity threshold, for certain values of threshold

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#1545]
**Internal**

**Summary**

When feeding nodes with a transaction workload, such that:

- the genesis has `maxBlockBodySize` set to 64000
- protocol is `TPraos`
- extra metadata payload (~100 bytes) is attached to transactions
- the load is sufficient to saturate the mempool so that full blocks are formed

..it's possible to trigger following errors in the nodes:
```
{"at":"2020-07-23T22:36:55.00Z","env":"1.17.0:00000","ns":["cardano.node.Forge"],"data":{"kind":"TraceStartLeadershipCheck","slot":893,"utxoSize":11875},"app":[],"msg":"","pid":"20429","loc":null,"host":"node-0","sev":"Info","thread":"46"}
{"at":"2020-07-23T22:36:55.00Z","env":"1.17.0:00000","ns":["cardano.node.Forge"],"data":{"kind":"TraceNodeIsLeader","slot":893},"app":[],"msg":"","pid":"20429","loc":null,"host":"node-0","sev":"Info","thread":"46"}
{"at":"2020-07-23T22:36:55.00Z","env":"1.17.0:00000","ns":["cardano.node.Forge"],"data":{"kind":"TraceForgedBlock","slot":893},"app":[],"msg":"","pid":"20429","loc":null,"host":"node-0","sev":"Info","thread":"46"}
{"at":"2020-07-23T22:36:55.06Z","env":"1.17.0:00000","ns":["cardano.node.ChainDB"],"data":{"queueSize":1,"kind":"TraceAddBlockEvent.AddedBlockToQueue","block":{"hash":"\"3bc53e8833eadd5c8010912187017f0ac65e5ffa2e4aa27591bf90281d1df907\"","kind":"Point","slot":893}},"app":[],"msg":"","pid":"20429","loc":null,"host":"node-0","sev":"Debug","thread":"46"}
{"at":"2020-07-23T22:36:55.09Z","env":"1.17.0:00000","ns":["cardano.node.ChainDB"],"data":{"kind":"TraceAddBlockEvent.AddBlockValidation.InvalidBlock","error":"ExtValidationErrorHeader (HeaderEnvelopeError (OtherHeaderEnvelopeError (HardForkEnvelopeErrFromEra Z (WrapEnvelopeErr {unwrapEnvelopeErr = BlockSizeTooLargeCHAIN 64021 64000}))))","block":{"hash":"\"3bc53e8833eadd5c8010912187017f0ac65e5ffa2e4aa27591bf90281d1df907\"","kind":"Point","slot":893}},"app":[],"msg":"","pid":"20429","loc":null,"host":"node-0","sev":"Error","thread":"36"}
{"at":"2020-07-23T22:36:55.09Z","env":"1.17.0:00000","ns":["cardano.node.ChainDB"],"data":{"kind":"TraceAddBlockEvent.AddBlockValidation.ValidCandidate","block":"\"7adc18bdfcb3ea4a76d568503dbba90de1f8b710999244de0bc037978c8b7f7d\"@875"},"app":[],"msg":"","pid":"20429","loc":null,"host":"node-0","sev":"Info","thread":"36"}
{"at":"2020-07-23T22:36:55.09Z","env":"1.17.0:00000","ns":["cardano.node.Forge"],"data":{"kind":"TraceForgedInvalidBlock","reason":{"kind":"ValidationError","error":{"kind":"HeaderEnvelopeError","error":{"blockSize":64021,"kind":"BlockSizeTooLarge","maxBlockSize":64000}}},"slot":893},"app":[],"msg":"","pid":"20429","loc":null,"host":"node-0","sev":"Error","thread":"46"}
```

**Steps to reproduce**
1. Have Nix installed (https://nixos.org/download.html) and configure IOHK Hydra as a binary cache (see https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md)
1. check out commit `e66e796651d1a1e17ad90dd3d10e3705a94ef397` from the following branch: https://github.com/input-output-hk/cardano-benchmarking/tree/block-body-size-repro
1. `nix-shell --no-build-output --cores 0 --max-jobs 4` inside the checkout
1. `sed -ni '1,/--- 8< ---/ p' "$(git rev-parse --show-toplevel)"/cabal.project`
1. `cd benchmarks/shelley3pools`
1. `./start.sh`

**System info**
- OS: NixOS Linux
- Version 21.09-pre
- Node version: 1.17 (`0191ff56d194b6ac074af0d51e67493c14e08ffa`)

**Comment by mrBliss** [comment]
With the help of @deepfire, I discovered that it is related to the presence of metadata in transactions.

When transactions contain metadata, the sum of the binary sizes of the individual transactions can be _smaller_ than the binary size of the block body ([`TxSeq`](https://github.com/input-output-hk/cardano-ledger-specs/blob/ed7acfc16efba51e10bad3e8fc7f19b043fd8a9a/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs#L156) in `cardano-ledger-specs`) consisting of exactly the same transactions. This means that when we take transactions out of the Mempool that together do not exceed the maximum block body size, the body of the block containing those transactions can actually exceed it.

(In fact, without metadata, the sum of the binary sizes of the individual transactions is typically _larger_ than the binary size of the corresponding block body.)

We never noticed this in the consensus tests because the transaction generator we use from `cardano-ledger-specs` [doesn't generate metadata](https://github.com/input-output-hk/cardano-ledger-specs/blob/be1e61ad0f73c099a8b9ca1be430e3b40706f398/shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Utxo.hs#L230). By locally modifying it, I have been able to reproduce the bug.

I'm still trying to find out what the precise cause of this discrepancy is.

I have been told we don't typically include metadata in transactions, so this is not a critical bug.

**Comment by mrBliss** [comment]
> I'm still trying to find out what the precise cause of this discrepancy is.

By comparing the CBOR of two transactions with the CBOR of the corresponding block body, I think I found the cause.

Each transaction consists of a tx body, a set of witnesses, and _optionally_ metadata. The serialised block body (`TxSeq`) consists of (for good reasons) a list of all tx bodies, a list of all witnesses, and a list of all metadata (as opposed to storing things interleaved, like a concatenation of the serialised transactions). Since metadata is optional, each piece of metadata in that list is [preceded](https://github.com/input-output-hk/cardano-ledger-specs/blob/ed7acfc16efba51e10bad3e8fc7f19b043fd8a9a/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs#L182) with the index of the transaction, so that when decoding the list, the metadata can be [mapped](https://github.com/input-output-hk/cardano-ledger-specs/blob/ed7acfc16efba51e10bad3e8fc7f19b043fd8a9a/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs#L512) to the right transactions again.

It's this extra index that is unaccounted for when estimating the block body size based on the transaction sizes.

I'll implement a fix.
