### ISSUE TITLE
[BUG] - cardano-cli calculate-min-fee with TTL isn't actually the min fee

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1556]
**Exernal**

**Summary**
When calling calculate-min-fee, I expect to be given the minimum fee to pay to make my transaction go through successfully. If I specify a TTL as if I'm going to submit the real transaction, the fee returned is higher than if I set a dummy value of 0.

However, if I send a real transaction with proper ttl and include the lower fee value (generated with 0 ttl), the transaction goes through. Therefore, calculate-min-fee doesn't actually calculate the minimum fee unless ttl is specified as 0.

**Steps to reproduce**
```
# calculate transaction fee WITH ttl
$ /home/westbam/.local/bin/cardano-cli shelley transaction build-raw --tx-in 0832f891bdceb8b925e73799e911ac612e2ff8782d1e19254deac12b297aeac9#0 --tx-out addr1qyftuwe6fww2eeg2k5quyzp099f5y6pn0snkneu5fdq6puqjuycagppd9yw3kc62xjld0c45a2ljc6d3tlnh96fut8ss67heqw+0 --tx-out addr1qyftuwe6fww2eeg2k5quyzp099f5y6pn0snkneu5fdq6puqjuycagppd9yw3kc62xjld0c45a2ljc6d3tlnh96fut8ss67heqw+0 --ttl 128126 --fee 0 --out-file /tmp/dummy.txbody 
$ /home/westbam/.local/bin/cardano-cli shelley transaction calculate-min-fee --tx-body-file /tmp/dummy.txbody --protocol-params-file protocol-parameters.json --tx-in-count 1 --tx-out-count 2 --testnet-magic 42 --witness-count 1 --byron-witness-count 0
176765 Lovelace

# calculate transaction with ZERO ttl
$ /home/westbam/.local/bin/cardano-cli shelley transaction build-raw --tx-in 0832f891bdceb8b925e73799e911ac612e2ff8782d1e19254deac12b297aeac9#0 --tx-out addr1qyftuwe6fww2eeg2k5quyzp099f5y6pn0snkneu5fdq6puqjuycagppd9yw3kc62xjld0c45a2ljc6d3tlnh96fut8ss67heqw+0 --tx-out addr1qyftuwe6fww2eeg2k5quyzp099f5y6pn0snkneu5fdq6puqjuycagppd9yw3kc62xjld0c45a2ljc6d3tlnh96fut8ss67heqw+0 --ttl 0 --fee 0 --out-file /tmp/dummy.txbody
$ /home/westbam/.local/bin/cardano-cli shelley transaction calculate-min-fee --tx-body-file /tmp/dummy.txbody --protocol-params-file protocol-parameters.json --tx-in-count 1 --tx-out-count 2 --testnet-magic 42 --witness-count 1 --byron-witness-count 0 
176589 Lovelace
```

**Expected behavior**
I expect when we calculate-min-fee, we actually calculate the minimum fee required for the transaction to go through.

**System info (please complete the following information):**
- OS: Ubuntu
- Version 20.04
- Node version 1.17.0

**Comment by SebastienGllmt** [comment]
> TTL as if I'm going to submit the real transaction, the fee returned is higher than if I set a dummy value of 0

This is by design. The fee calculation for a function is a linear function aX+b where X is the size of the transaction in bytes. Cardano uses an encoding called CBOR which tries to minimize the amount of bytes taken for data (unlike JSON, for example, which is very space inefficient).
One of the features of CBOR is that integers take a different number of bytes depending on their value. That's why setting the TTL as "0" takes less bytes than the real number you want to set.
Cardano allows setting a fee higher than the minimum value, so if you want you can calculate a fee setting the maximum possible value for a ttl and it guarantees the real value used will take fewer bytes.

**Comment by AndrewWestberg** [comment]
Thanks for the explanation. Closing...
