### ISSUE TITLE
[BUG] - Epoch Boundary High ram / cpu stuck

### ISSUE THREAD

**Issue by glitch40** [input-output-hk/cardano-node#1583]
Exernal

**Summary**
Relays after epoch transition CPU's show heavy load and ram climbs from low amount prior to transition to 3GB or greater usage and sticks until node reset.  This has been reported to crash nodes on epoch transition,

This crashes minimum suggested spec nodes with dual cpu and 4gb ram not running large swap files, nodes with more resources continue to function but the ram usage sticks to several GB (3-4) in most cases until the node is restarted. The core did also increase in ram usage. 

**Steps to reproduce**

restart node before epoch transition and observe 

**System info (please complete the following information):**
- OS:  Ubuntu 
- Version   20.04 /18.04
- 1.18.0 ba0f96b

default logging is disabled so i do not have logs however this has happened on several nodes and should be repeatable.

**Comment by monkolli** [comment]
I am also seeing this heavy load issue with minimum spec nodes on 1.18.0 and Ubuntu 20.04. But not all of them. In addition, my experience is if the machine passes the epoch boundary resource use recovers to normal after without node restart.

This occurs only on my (identical) nodes that are showing 23-24 or greater connected peers (excess of 20 recommended peers as a result of what topologyUpdater.sh returns after the valency is factored for on cardano-node start) 

One example had 26 peers and consumed 4GB of RAM and 2GB Swap within moments of the epoch boundary being hit at which point cardano-node was killed

Also have logging disabled at present so nothing further to share.

**Comment by feqifei** [comment]
I confirm, all my 8 relays have a spike at the time of epoch change. Those ones on small vm sometimes crash with a "killed process" message.
![image](https://user-images.githubusercontent.com/42180581/88685687-ca3b4380-d128-11ea-90be-c565eaa44ea3.png)

**Comment by zenithpool** [comment]
I am currently running cardano-node v1.18 on Docker/Kubernetes and have been for at least a day. I give each container a guaranteed 1vcpu and a requested 1GB of memory with a limit of 3GB. I do notice these spikes in usage but they have never crashed.

![image](https://user-images.githubusercontent.com/56691430/88695906-291ca080-d0c8-11ea-9c13-af2b550775bd.png)

You can view the dashboard at https://grafana.fra.zenithpool.io/d/XlUdwmZGk/cardano-monitor?orgId=1&from=now-24h&to=now&refresh=5s

**Comment by Scitz0** [comment]
I noticed that memory climbed on all nodes at epoch cutover from 208 -> 209. Both relays and BPs.
The fact that memory increase on epoch boundary is expected with the calculation that is needed but the questions are, is the extra allocated memory released again by GC. So far it does not seem to be.

Graph show RSS memory consumption and how it jumped up at epoch switch. Has stayed at the increased usage since then. 
![image](https://user-images.githubusercontent.com/15903629/89238694-3ae5d280-d5f7-11ea-9432-2aee665e5c59.png)

**Comment by glitch40** [comment]
Its more noticeable on the "suggested" spec machines with 2c 4gb on 208 -> 209 Again the ram creeps up through epoch leading to the transition which will max the ram usage on the instance then ram will continue to be used and not released as Scitz0 displaed above.  The smaller nodes (4gb ram) risk spikes at the calculation that crash the node from being OOM mine are still at 3.68GB usage hours after the transition which remains unless forced restart or crash on next epoch transition.

**Comment by latheesan-k** [comment]
I am seeing memory usage in ~6gb for the whole box (when node isn't running, all the box only uses ~150mb ram)

![image](https://user-images.githubusercontent.com/6196415/89285797-ed925100-d648-11ea-9fc8-5ce21d99b969.png)

**Comment by zenithpool** [comment]
I have been running multiple instances cardano-node 1.18.0 on docker with a memory limit of 10 GB. After the epoch transition, I  noticed a huge spike in usage with the relay at 5GB of memory. Still monitoring... They did update the release notes and noted that for stake pools the [suggested memory limit is 8GB](https://github.com/input-output-hk/cardano-node/releases/tag/1.18.0)

![image](https://user-images.githubusercontent.com/56691430/89312562-06950500-d63d-11ea-86d9-0ee599d409f9.png)

**Comment by mestakepool** [comment]
TICKER : ADAGL, GLNET - ADA Globe Network

I have some observation to share If it could help. I have relays at US, Dubai and Singapore. I am assuming that snapshot trigger would have happened from some data center in US since the block chain is federated currently. (I could be wrong). Below is the observation.

CPU / Memory spike started in following order 
1. US
2. Singapore
3. Dubai

Though all nodes are not releasing memory currently (this could be a separate problem), I can see that US node stabilized fast followed by Dubai and then Singapore.

Just assumption from my side is below. 

Latency order            --> US --> Singapore ---> Dubai  (low latency to high)
Snapshot start order --> US --> Singapore ---> Dubai

High peers order ---> US (400+ peers) --> Dubai (Most EU peers) --> Singapore (Less peers)
Snapshot completion order --> US --> Dubai ---> Singapore

Memory release issue: 
High in Singapore 
Medium in Dubai
Low in US

All my relay servers are having same specification running only Cardano node. Number of peers connected to all nodes are almost same for my servers. (around 18 - 20)


Attachments below.  I am not sure memory issue has anything to do with relays density across globe but thought worth mentioning here...I could be wrong :)

![Relays CPU](https://user-images.githubusercontent.com/65891807/89444065-3558cb80-d762-11ea-958f-f27e55ebd4a2.jpg)
![Relays Memory](https://user-images.githubusercontent.com/65891807/89444116-473a6e80-d762-11ea-8c01-8f6a2fa73f86.jpg)

**Comment by chadle-git** [comment]
I also experienced the same issue during the 2 new Shelley Epoch's. Running 4GB of mem and 2 cpus. It killed itself both times.
![image](https://user-images.githubusercontent.com/60274638/89860788-e3e97b80-db69-11ea-951b-f8707fcbfe1f.png)

**Comment by vix-io** [comment]
hi @glitch40 we've made some significant improvements, we`ll close this ticket. If you are still seeing the issue, please open a new ticket.
