### ISSUE TITLE
[FR] -Display "Producer" or "Relay" in Live Mode 

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-node#1694]
**Internal/External**
*External*   

**Describe the feature you'd like**
Add an indicator as to whether the node is a producer or relay.

**Comment by vix-io** [comment]
We've added this to our backlog

**Comment by denisshevchenko** [comment]
Since `LiveView` is officially deprecated and will be removed from the node very soon, I'm closing this issue. Please check [RTView](https://github.com/input-output-hk/cardano-rt-view/), our new tool for real-time watching for Cardano nodes. Its repository already contains this [feature request](https://github.com/input-output-hk/cardano-rt-view/issues/2), it will be implemented in future releases.
