### ISSUE TITLE
[FR] Support for multiple leader keys

### ISSUE THREAD

**Issue by aftershowrc** [input-output-hk/cardano-node#1795]
Can we have a single instance of cardano-node be a leader for multiple pools, like we had in Jormungandr? For some of us it would be a large operating cost saving.

Jormungandr Example:
jormungandr --config config.yaml --secret pool1.yaml --secret pool2.yaml

**Comment by kevinhammond** [comment]
I'm not sure whether this is technically possible with the current design: @dcoutts should be able to comment on that.  It would involve some code restructuring at least, I expect.

**Comment by dcoutts** [comment]
My opinion is that it doesn't make any sense for a real deployment :smile: 

It adds no decentralisation at all. Even if a single entity runs multiple pools (which looses some organisational decentralisation), they should at least be physically decentralised, e.g. running in different data centres. They should certainly not be run on the same machine or in the same process. We can't stop people from doing silly things like running them on the same physical host, but there's no need to make that an easy or encouraged thing to do.

IMHO it reallyt ought to be up to operators that run multiple pools to provide evidence to the public that they at least have some network decentralisation for the pools they operate, since of course they're not adding so much organisational decentralisation.

**Comment by aftershowrc** [comment]
Fair point, closing.
