### ISSUE TITLE
[FR] - iptables DDoS filter compatible with node relay behaviour?

### ISSUE THREAD

**Issue by rphair** [input-output-hk/cardano-node#1815]
**Internal/External**
*External*
**Describe the feature you'd like**
*An official response while waiting for documentation (in the `cardano-node` setup documentation) of what, if anything, to do about the case below.*

There was a penetration test announced a few hours ago on the Cardano Forum which, according to the way it was originally worded, sounded as if it were non-consensual.  Hence the creation of this issue which appeared to be urgent according to the information that was available at the time (we might otherwise have arrived at a consensus on the forum itself, hopefully with IOHK developer participation).

That test was to see if relay nodes could be taken out of service by connection floods on the Cardano port: https://forum.cardano.org/t/tips-to-improve-stake-pool-node-security/39918/3

If we were to adopt the tester's suggestion of "limiting number of connections from one ip per port (sic)", would limiting the connections as such (on relays only) interfere in any way with the legitimate protocol as relays are expected to behave?  Something like:

`iptables -A INPUT -p tcp --syn --dport 3001 -m connlimit --connlimit-above 1 --connlimit-mask 32 -j REJECT --reject-with tcp-reset`

Maybe `DROP` would be more appropriate than `REJECT`, or a limit greater than `1`, to help preserve any legitimate activity.  In any case this is way above my level with respect to the network behaviour of the node, so we don't want to consider this without guidance.  We're hoping for developers' advice about this while the issue is still fresh on the Cardano Forum.

**Comment by dcoutts** [comment]
@karknu any opinions?

**Comment by karknu** [comment]
I can think of two setups that that would break with such a limit.
1: People that run multiple relays on the same server. This is not something that we want to encourage since it offers little additional redundancy.
2: End users behind CGNAT. This is a group of users that we do care about.

Limiting the number of incoming connections per IP address is fine, but the limit SHOULD be larger than 1 and the response SHOULD be a TCP reset.

With a limit larger than 1 it means that a relay can support some number of end users behind CGNAT.
The TCP reset response means that valid clients behind CGNAT can detect an overloaded relay at once and pick another peer to connect to.
