### ISSUE TITLE
500 Ada Pool deposit lost if Rewards address is ever de-registered

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/cardano-node#1821]
I retired a pool and then de-registered the owner staking address and the rewards staking address. After realizing that the 500 ada deposit was supposed to be returned to the rewards address, I re-registered it on the chain. After the pool retired, no 500 ada back. 

https://pooltool.io/pool/3b066c31e418ae43a63b621c148ffc076ad6c0715c1079790a0209f0
```
PoolID: 3b066c31e418ae43a63b621c148ffc076ad6c0715c1079790a0209f0
Owner Payment Address: addr1q9lwmtrrwamrgj7zadh0vz2e9cgxq99yley5f5h59s5x0vk0svw555dv93ag9jz3q8t89runhglpt43u2v7xs8hxff6sn0px4x
Owner Staking Address: stake1u88cx8222xkzc75zepgsr4nj37fm50s46c79x0rgrmny5ag9l92vy
Rewards Payment Address: addr1qyfgenmpkgz7vh3zjxz834lf2gqmvfxw2ae2juxpwch84lmyawmlck8cw87wp8xxan4g0wtrd7qryd45murg24etawjqf3am8r
Rewards Staking Address: stake1u9jwhdlutru8rl8qnnrwe658h93klqpjx66d7p592u47hfq5pdejf
```

**Comment by nc6** [comment]
Transferred to `cardano-node` for triage and priority assignment!

**Comment by dcoutts** [comment]
Basic advice obviously: don't do this :-)

From a brief reading of the ledger rules however, it looks to me like it ought to work if the stake address is re-registered in time. The POOLREAP transition (Fig 41) just needs the retiring pool to reference a registered stake address. And unregistering the stake address does not adjust the pools state at all. So it looks like it should work to re-register.

@JaredCorduan any thoughts? Am I misreading the spec?

**Comment by JaredCorduan** [comment]
> I retired a pool and then de-registered the owner staking address and the rewards staking address. After realizing that the 500 ada deposit was supposed to be returned to the rewards address, I re-registered it on the chain. After the pool retired, no 500 ada back.

When you say that you "re-registered it", do you mean the owner stake credential, the reward stake credential, or both? The deposit goes back to the reward stake credential.

> @JaredCorduan any thoughts? Am I misreading the spec?

I don't think so.  If the stake address that was listed in the stake pool registration certificate for the pool's rewards was re-registered in time it should have worked. There is still exactly 45B ada in the system, so that deposit [either](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs#L100) went to the address listed in the pool registration cert or was deemed unclaimed.

The possibilities of what went wrong are, as far as I can tell: it was the owner stake credential that was re-registered (not the reward one), or the stake credential re-registration did not get included in time.

**Comment by AndrewWestberg** [comment]
I re-registered the reward stake address.

**Comment by AndrewWestberg** [comment]
stake1u9jwhdlutru8rl8qnnrwe658h93klqpjx66d7p592u47hfq5pdejf

**Comment by JaredCorduan** [comment]
https://pooltool.io/pool/3b066c31e418ae43a63b621c148ffc076ad6c0715c1079790a0209f0 is showing that the reward account is:
```
e164ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4
```
(I guess pooltool remembers pools after they retire?)

I looked at two ledger state dumps that I happened to have lying around, one from Aug 28th and one from today. Both showed that that reward account was not registered.

Did you de-register it a second time? Do you know about what day you first de-registered it, and what epoch the pool retired?

**Comment by AndrewWestberg** [comment]
@JaredCorduan That is the correct rewards account. I'm showing it on chain. I did not de-register it a second time. It was de-registered once, and then re-registered. I haven't touched it since.

**Comment by JaredCorduan** [comment]
@AndrewWestberg if you never intentionally de-registered it a second time, then I think that something must have gone wrong with the re-registration.  you can see for yourself that `e164ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4` is not currently registered by inspecting a ledger state dump:
```
$ cardano-cli shelley query ledger-state --mainnet | grep e164ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4
```
If it were currently registered, you would see grep find several matches, but when I run the above command I get nothing.

You are referring to a series of events on mainnet, correct?

**Comment by AndrewWestberg** [comment]
@JaredCorduan It is on the chain. You need to remove the `e1` from the beginning as that's a bech32 artifact.

```
$ cardano-cli shelley query stake-address-info --address stake1u9jwhdlutru8rl8qnnrwe658h93klqpjx66d7p592u47hfq5pdejf --cardano-mode --mainnet
[
    {
        "address": "stake1u9jwhdlutru8rl8qnnrwe658h93klqpjx66d7p592u47hfq5pdejf",
        "delegation": null,
        "rewardAccountBalance": 0
    }
]
```

```
$ cat /tmp/ledger-state.json| grep 64ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4   
                            "key hash": "64ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4"
                            "key hash": "64ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4"
```

**Comment by JaredCorduan** [comment]
> @JaredCorduan It is on the chain. You need to remove the `e1` from the beginning as that's a bech32 artifact.

you are totally right, thank you @AndrewWestberg !

After digging around in some ledger state dumps, I see that pool `3b066c31e418ae43a63b621c148ffc076ad6c0715c1079790a0209f0` was registered in epoch 212, and set to retire in epoch 213. Epoch 213 began at 2020/08/23 21:44:51 EST, so the stake key `64ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4` would need to have been re-registered before then. I have a dump dated about thirty minutes before the epoch change at 2020/08/23 21:15:38 EST that shows that it is not registered. The next dump that I have easy access to is from 2020/08/27 19:47:35 EST, and I do see the stake key registered by then. Unfortunately it's a bit time consuming for me to get dumps at particular times, but what I need to check next is if the key was registered between 21:15 EST and 21:44 EST on 2020/08/23. If it didn't make it into this 29 minute window, then everything is working as expected.

**Comment by JaredCorduan** [comment]
@AndrewWestberg I have confirmed that `64ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4` was not registered when epoch 213 began, which was when the pool was reaped.

Here is what I did. I added a [small change](https://github.com/input-output-hk/cardano-ledger-specs/commit/ec5f7b7d70e4418e96a4fa54aa4df582e1c4a5a1) to the ledger code so that the node would raise an error on the first block processed in epoch 213, and then dump the currently registered reward accounts.  I then built a full node, nuked the database, ran the node from genesis, and captured the error. To sanity check myself, I checked my personal reward account in the error message to see that it was as I would expect for epoch 213. I then looked to see if `64ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4` was registered, but it was not.

It looks like `64ebb7fc58f871fce09cc6ecea87b9636f803236b4df0685572beba4` was registered sometime between 2020/08/23 21:44:51 EST and 2020/08/27 19:47:35 EST, which is too late to get the deposit back.

I'm sure it's a bummer to have attempted to get the deposit back and it not work out. :(

**Comment by AndrewWestberg** [comment]
@JaredCorduan Thanks for the thorough investigation. I'm going to go ahead and close this ticket.

**Comment by ahaxu** [comment]
I have the same issue, this is my old payment.addr
```
addr1q8k3ry4l0awkn0fgfq7znyj8pe78f5d6r3hh8t632a9p6ut7nf88klg69dfutch8r095eprqg8fr67a77nydazqx4k3qn3aat7
```
and this is my pool deregistration cert

```
{
    "type": "CertificateShelley",
    "description": "Stake Pool Retirement Certificate",
    "cborHex": "8304581c3d6c43ce268e05c0bf038dd3364ae0eba2e97d6e9e1b2801f2c51864190100"
}
```

this is the transaction for the first time pool registration
https://cardanoscan.io/transaction/c7bbec808dcdad3cf854e00044ffcfc73ae2e30d915d87cb5bbd0befd2a496ad?tab=poolcertificates

Can you help to check this. my pool ticket is **AHA**

**Comment by jbpin** [comment]
Guys you need to do something for that ! I have the same issue.. you should prevent stake dereg for active pool.. how we can now? Any chance to get the deposit back?

**Comment by rodmarzavala** [comment]
Hello guys! I have the same issue, I de-register my pool (on epoch 273) and did not receive rewards.
Can anyone help me?

My Pool: 73946f2e9cd318983c5e846a1d5f0b828a49916861a6ea405b07457c

Thanks

**Comment by vader** [comment]
Same issue too...
