### ISSUE TITLE
[BUG] - cardano-node relay on MacOS sometimes dies with SystemClockMovedBack error

### ISSUE THREAD

**Issue by stakelovelace** [input-output-hk/cardano-node#2138]
I've been running latest master build of cardano-node on my Macbook for a while, every now and then the node just dies - the command prompt from where it was launched shows:

cardano-node: ExceptionInLinkedThread "ThreadId 41" (SystemClockMovedBack (SlotNo 14912403) (SlotNo 14912400))

Given I don't actually do any clock adjusting on my laptop, would be good to know what's causing it and how to avoid it.

**Comment by mrBliss** [comment]
We have had another report of this on MacOS. I heard from someone that:
> Apple don’t work hard to keep system time monotonic or accurate

Maybe there was a larger than usual system time adjustment recently?

In the Byron era with 20s slots, we could tolerate the system time moving up to 20s (exclusive) back, but now in the Shelley era with 1s slots, we only allow the time to move up to 1s (exclusive) back.

So the chances of seeing `SystemClockMovedBack` in the Shelley era are much larger. Because of this, we will do something about it: https://github.com/input-output-hk/ouroboros-network/issues/2781

**Comment by CarlosLopezDeLara** [comment]
Fixed in https://github.com/input-output-hk/ouroboros-network/pull/2785
