### ISSUE TITLE
[BUG] - InFutureExceedsClockSkew - I am not sure this is a bug, just not a FR

### ISSUE THREAD

**Issue by adrem1** [input-output-hk/cardano-node#2139]
**External**
SPO for rabbitholepools.io [RABIT]
**Summary**
Following system reboot, relay node starts, syncs but immediately drops all outgoing connections and gets dropped by all incoming peers (no txn flow), with error in log file as follows:

 {“at”:“2020-11-27T01:23:55.33Z”,“env”:“1.21.1:9577e”,“ns”:[“cardano.node.ChainDB”],“data”:{“kind”:“TraceAddBlockEvent.IgnoreInvalidBlock”,“block”:{“hash”:“5956c15”,“kind”:“Point”,“slot”:14873950},“reason”:“InFutureExceedsClockSkew (RealPoint (SlotNo 14873950) 5956c15ab55ef0f89d6d43d4e6e03a328ee158f28168471f15320dcceb6ae5c0)”},“app”:,“msg”:"",“pid”:“696”,“loc”:null,“host”:“ip-172-3”,“sev”:“Info”,“thread”:“39”}

More log info attached as separate file.

**Steps to reproduce**
1. Have cardano-node run as systemd service with unit as specified in attached file
2. Reboot system

**Expected behavior**
With the attached systemd unit, I have never experienced any issues starting/stopping/restarting the cardano-node. This applied to system-wide reboots also. Until Wednesday, Nov 25 2020, which is when this issue first presented (I have been using systemd for months, including testnet). I would have expected a system-wide reboot to be followed in quick succession by a start of cardano-node (within 45 seconds of rebooting). This always worked. The other day it didn't with error as above (and attached in logs).

At first glance I thought this was a time sync issue. So I discovered this:

1) the issue went away with a reset of the whole db (but replicated at the next reboot);
2) the issue did not seem to occur if the server was shut down and restarted (instead of reboot).

I decided to attempt to install chrony, and this, surprisingly solved the problem. I have attempted to replicate the issue and have not managed. Since then I have also successfully updated to 1.23.0 without a hitch.

[IOHK_request_20201127.txt](https://github.com/input-output-hk/cardano-node/files/5612047/IOHK_request_20201127.txt)
[reboot_fail_cardano_InFuture.txt](https://github.com/input-output-hk/cardano-node/files/5612048/reboot_fail_cardano_InFuture.txt)
[systemd_service.txt](https://github.com/input-output-hk/cardano-node/files/5612049/systemd_service.txt)

**System info (please complete the following information):**
- OS: Ubuntu
- 20.04
- 1.21.1

**Screenshots and attachments**
Please see attached systemd unit and log file snippet. Please let me know if you require more information.

**Additional context**
I have already posted this issue on the forum:  https://forum.cardano.org/t/system-time-sync-issue-causing-relay-wreck/42607
I have also opened a ticket with IOHK on Zendesk (106428 -attached).

Thank you for your time and patience.

All the best,

Adrem

**Comment by mrBliss** [comment]
The error you see is there to protect you from dishonest nodes setting their clock ahead so that they're *in a future slot*, which increases their chances of winning slot battles or just to make you adopt their chain, as it can be longer.

We do allow for *some* clock skew (a few seconds) as in practice not all nodes will have perfectly synchronised clocks. However, when we receive a block created in a slot that is unreasonably far in the future, we treat it as invalid (`InFutureExceedsClockSkew`).

It is very likely that this happened *not* because some dishonest node served you a block created in a future slot, but because *your clock was running behind*. This meant that blocks created by honest nodes were incorrectly considered as invalid.

> I decided to attempt to install chrony, and this, surprisingly solved the problem.

With the explanation above, maybe you'll find this less surprising? :slightly_smiling_face: 

> the issue went away with a reset of the whole db (but replicated at the next reboot);
Note that in such cases, deleting the `volatile` folder will very likely be enough, and won't require you to sync the whole chain again, just a few thousand blocks.

We expect people to keep their clocks in sync. Most OSes or distros enable NTP or another daemon by default anyway. If we can't rely on this, how else could we detect the attack described above? We would have to incorporate some kind of NTP functionality ourselves. FYI, Ouroboros Chronos should take care of this too. So this is not a bug.

**Comment by adrem1** [comment]
@mrBliss,

thank you for taking the time to clarify this issue with me. Really appreciate it! 

I have taken the liberty to link this closed issue on the forum, where it appears as a solution. I hope it's OK.

All the best,

A
