### ISSUE TITLE
[FR] - Expose api function to compute the min ADA required for a token bundle

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#2298]
Provide a function in `cardano-api` for computing the minimum ada quantity required for a token bundle in a transaction output.

The ledger provides the `scaledMinDeposit` function: https://github.com/input-output-hk/cardano-ledger-specs/blob/b23e200632670de00e12c72d4e3e5bbddd985b70/shelley-ma/impl/src/Cardano/Ledger/ShelleyMA/Rules/Utxo.hs#L109

The api should expose a function of type: `Value -> Lovelace`

**Comment by dcoutts** [comment]
We should also add a CLI command to expose this functionality.

**Comment by jonathanknowles** [comment]
Hi @dcoutts, @Jimbo4350 

We also need to compute this quantity in the wallet, in order for coin selection work correctly.

In particular:

- When processing **user-specified outputs**:
    - If an output has a **zero-valued ada quantity**, we need to augment that output with a minimal ada quantity. 
    - If an output has a **non-zero-valued ada quantity**, we need to check that the output has an ada quantity greater than or equal to the minimal ada quantity.
- When generating **change outputs**:
    - We need to ensure that each change output has an ada quantity greater than or equal to the minimum.

I think it would be ideal to be able to call the function defined by the Cardano API, instead of rolling our own.

**Comment by jonathanknowles** [comment]
@dcoutts @Jimbo4350 

We've solved this issue in the wallet by calling the `scaledMinDeposit` function exported by the ledger specification:

https://github.com/input-output-hk/cardano-wallet/blob/736ad578d948ca2ddbad1ee050349f04f1533abf/lib/shelley/src/Cardano/Wallet/Shelley/Compatibility/Ledger.hs#L259-L283

This currently works well for us, because the ledger spec's representation of a token bundle is very similar to the one we use in the wallet. (A nested map, with the ada quantity stored separately.)

We test this with:

https://github.com/input-output-hk/cardano-wallet/blob/736ad578d948ca2ddbad1ee050349f04f1533abf/lib/shelley/test/unit/Cardano/Wallet/Shelley/Compatibility/LedgerSpec.hs#L84-L102

So it's currently less urgent than before for us to use the node API for this. (Although we could potentially switch in future.)

**Comment by gitmachtl** [comment]
May i ask why this FR was closed? We still don't have a calculation solution here to do it on the CLI.
