### ISSUE TITLE
[FR] - make `address build` accept scripts

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#2333]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Token Locking*    Related to Token Locking (Allegra).

**Describe the feature you'd like**
Currently, there's no way to generate a script address that isn't a payment only credential. That's currently done using `cardano-cli address build-script`.

Talking to ledger team, a script can be used as the payment credential, the stake credential or both, so my suggestion is we get rid of `address build-script` and add the additional `--payment-script` and `--stake-script` parameters to `address build` and have a requirement that you can only specify a `--payment-script` or a `--payment-verification-key-file` but not both and same rule for stake.

This is required for token locking to support continuing to stake to an address which is critical for catalyst fund4.

Example commands:
```
cardano-cli address build --payment-script foo.script --stake-script bar.script
cardano-cli address build --payment-verification-key-file foo.vkey --stake-script bar.script
cardano-cli address build --payment-script foo.script --stake-verification-key-file bar.vkey
```

**Describe alternatives you've considered**
Write my own code to generate an address. (we probably will in voting-tools, but would be good to have this ability in CLI as well and would make it possible for devops to test the feature prior to writing the code)

**Additional context / screenshots**

**Comment by dcoutts** [comment]
There's two sensible approaches:
1. keep the cli split between address build and address build-script, and extend address build-script to take the same flags as address build does for the stake reference part.
2. merge them together and allow either a key or script for the payment part, and either a key or script for the stake part.

I think overall 2 makes more sense since there's really 6 combinations:
* Payment: either key or script.
* Stake: either none, key or script.

Given that there's all possible combinations 2x3, then having it in a single command is probably simpler.
