### ISSUE TITLE
[BUG] - ValueNotConservedUTxO on pool registration updates

### ISSUE THREAD

**Issue by ttupper92618** [input-output-hk/cardano-node#2380]
*External*

**Area**
*Other*

**Summary**
I'm trying to update my pool margin.  I'm following the guide located at https://www.coincashew.com/coins/overview-ada/guide-how-to-build-a-haskell-stakepool-node#18-4-changing-the-pledge-fee-margin-etc

These steps essentially create a transaction with your ADA balance as input and your balance minus fee as your output.  As an example, I have two input Tx that total 2677700273.  The TxOut is 2677500232, which is the input minus the fee. 

I am creating a pool and deleg cert based on the same params as my initial registration, with a lower margin.  Then I am signing it.

When I submit the transaction, 1.25.1 comes back with:

`Shelley command failed: transaction submit Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (DeltaCoin 2677700273) (DeltaCoin 3177700273))))]`

Note that the second DeltaCoin value is exactly 500,000,000 lovelace greater than the first - that’s the pool registration fee. But I’m not registering; I’m just changing my margin. Moreover, that value was not even in my tx in or out - I literally have no idea where it came from.

This feels like a bug in 1.25.1.  It essentially prevents pools from updating their pool registration to lower margin, change pledge, etc.

**Steps to reproduce**

For a previously registered pool for which you have the original pool pledge, pool cost, keys, and metadata locale...
1. Follow the steps at https://www.coincashew.com/coins/overview-ada/guide-how-to-build-a-haskell-stakepool-node#18-4-changing-the-pledge-fee-margin-etc
2. Observe the TxIn and TxOut amounts
3. Continue on to creating a tx, signing it, and submitting to the network

As I said, this seems like a bug.  It seems like for pool registration transactions, 1.25.1 always expects the pool registration fee.  Unless there is a new method by which a pool operator can change their pool details, this completely breaks any chance of updating pool information.  I do not believe this is a problem with the provided guide; this also happens when following the directions in your docs.  This looks like either a bug, or as if an undocumented change in the method for altering a pool's registration has occurred.

**Expected behavior**
I expect a pool registration that contains inputs and outputs that include the fee but not the pool registration fee... to modify the pool registration.

**System info (please complete the following information):**
- Ubuntu
- 20.04
- 1.25.1

**Screenshots and attachments**
None - see above

**Additional context**
None

**Comment by ttupper92618** [comment]
Please note: this happens when the instructions in your own docs are followed also.

**Comment by rdlrt** [comment]
Have you considered before considering it bug that you're possibly using a different key/certs as input - thereby causing it to create a different pool? Heaps of folks are updating their pool params fine on 1.25.1 (as you can see via pool explorers), makes me believe the 'bug' is possibly human with the keys you're providing to the transaction build command

**Comment by ttupper92618** [comment]
> Have you considered before considering it bug that you're possibly using a different key/certs as input - thereby causing it to create a different pool? Heaps of folks are updating their pool params fine on 1.25.1 (as you can see via pool explorers), makes me believe the 'bug' is possibly human with the keys you're providing to the transaction build command

I don't think that's it.  I can send other TX just fine, I just can't update pool registration.  Also this problem is being actively discussed on the cardano forums, with others also people reporting it.  If this were an issue of keys, then wouldn't I also be unable to sign and send other TX?

If you look at the text of the bug, you can see that the balance and txOut are 2677700273 and 2677500232, respectively.  Yet the DeltaCoin values are 2677700273 and 3177700273.  Where did that second number come from?  It wasn't in the tx at all.  It's exactly 500 ADA > the tx out, which makes no sense.

**Comment by 0percentpool** [comment]
This generally happens when operators sign the wrong transaction due to copy paste. Make sure you create the transaction `tx.raw` before signing rather than `tx.draft`.

**Comment by ThrDragon** [comment]
I also can't update my pool cert on a `1.26.2` node. This seems like a bug, I've changed nothing in my workflow.

**Comment by cardsfan7189** [comment]
I just recently started building and registering nodes on 1.26.2 (just testnet right now) and getting the same ValueNotConservedUTxO error when I try to submit the pool and delegation certificates to the testnet blockchain. I've been following the guide at https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/register_stakepool.html.  Maybe it's a bug, maybe it's my error.  Although if ThrDragon hasn't changed the workflow, maybe it's not human error.  I've run the sequence of scripts three times, including the calculation of change, and I'm sure I have the right amounts.  The draft script

cardano-cli transaction build-raw \
--tx-in 15...#0 \
--tx-out $(cat payment.addr)+0 \
--invalid-hereafter 0 \
--fee 0 \
--out-file tx.draft \
--certificate-file pool-registration.cert \
--certificate-file delegation.cert

Calculating the fee
cardano-cli transaction calculate-min-fee \
--tx-body-file tx.draft \
--tx-in-count 1 \
--tx-out-count 1 \
--witness-count 3 \
--byron-witness-count 0 \
--testnet-magic 1097911063 \
--protocol-params-file protocol.json

which resulted in a fee of 196125 Lovelace
Calculating change back based on the 1000 ADA from balance and the 500 ada deposit to register, and the fee, the change back is 499803875 lovelace. 

Script to build actual transaction
cardano-cli transaction build-raw \
--tx-in 15...#0 \
--tx-out $(cat payment.addr)+499803875 \
--invalid-hereafter 25384566 \
--fee 196125 \
--out-file tx.raw

then signed the transaction

cardano-cli transaction sign \
--tx-body-file tx.raw \
--signing-key-file payment.skey \
--signing-key-file stake.skey \
--signing-key-file cold.skey \
--testnet-magic 1097911063 \
--out-file tx.signed

then submitted

cardano-cli transaction submit \
--tx-file tx.signed \
--testnet-magic 1097911063

And I get this
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraMary (ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 1000000000 (fromList [])) (Value 500000000 (fromList [])))))])

A couple of days ago, also on 1.26.2, I was able to successfully return ADA to the testnet faucet, so that transaction worked.

**Comment by cardsfan7189** [comment]
Also posted at https://forum.cardano.org/t/issue-updating-pool-certificate-valuenotconservedutxo-on-pool-registration-updates/59046/4, and got the workaround, calculated the fee without the 500 deposit.  So it's working now, but seems strange.

**Comment by ThrDragon** [comment]
That's not a workaround, that's just how it works. IIRC, the 500 ADA deposit has always just been: add 500 ADA (as if the TX won't balance), and then it just works (which is kind of a weird UX quirk)

This issue is about a pool that is already registered, not being able to update because cardano-cli wants the deposit a second time.

**Comment by luisg707** [comment]
I am +1'ing this bug. 

New registration. Paid 500 ADA to register. During my first modify, i was unable to update it, as i keep getting the same error: 

`2021-05-03 23:42:48 UTC [ERROR]  Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraMary (ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 100014000000 (fromList [])) (Value 100514000000 (fromList [])))))])`

Which is exactly 500 ADA. If i try to pay the 500 ADA again, The number keeps bumping up 500+ ada for whatever i put.

**Comment by laplasz** [comment]
@luisg707 so the pool deposit - 500 ADA - is missing from the txOut calculation:
https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/register_stakepool.html#calculate-the-change-for-tx-out
try the registration again by subtracting the poolDeposit from the balance -
```
echo stakePoolDeposit: $stakePoolDeposit
stakePoolDeposit: 5000000000
txOut=$((${total_balance}-${stakePoolDeposit}-${fee}))
echo $txOut
```
txOut should be 100014000000 as the error suggesting instead of 100514000000..

**Comment by luisg707** [comment]
@laplasz This is a Pool Modify, not a new pool registration. Pool is operational in adapools. Do I need to still subtract the balance even though it was paid 2 epoch's ago?

**Comment by laplasz** [comment]
@luisg707 - try to verify that the cold.key used during cert creation gives back the registered pool id
`cardano-cli stake-pool id --cold-verification-key-file cold.vkey --output-format "hex"`
or maybe the stake cert is different - but I dont think that it involve a new registration...

**Comment by luisg707** [comment]
@laplasz  That was it! I am not sure how the cold key got overwritten to a new value, but bless backups. 

I wonder if this GitHub issue by OP is really just that- the Cold.skey/vkey dont match the blockchain, and it's barking to re-pay the 500 ada. 

This is a good sanity check for anybody in the same scenario. 
https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/register_stakepool.html#verify-that-your-stake-pool-registration-was-successful
