### ISSUE TITLE
[FR] - Number of coders

### ISSUE THREAD

**Issue by europound** [input-output-hk/cardano-node#2402]
How come you have got only 4 developers for such large project?
Ethereum got 2 000 developers working around the clock
What is happening?

**Comment by matiwinnetou** [comment]
Cardano Community response: What makes you think this? There are hundreds developers and scientists working on Cardano.

Please close this as this is not relevant...

**Comment by europound** [comment]
I propose to increase dev count by x10
plenty of money at CEO

**Comment by europound** [comment]
it has been 6 months+ but trezor t hardware wallet passphrase is still not working, which is essential key core element

**Comment by erikd** [comment]
> How come you have got only 4 developers for such large project?

That is not correct, for a number of reasons:

* There have been over 70 contributors to this repo, the vast majority of them employed by IOHK.
* This repository is not the whole project. This repository uses a number of other repositories as libraries and those other repositories also have large contributor lists.

> Ethereum got 2 000 developers working around the clock

Maybe, but how effective are all those developers? It has been known since the 1970s (see the book [The Mythical Man Month](https://en.wikipedia.org/wiki/The_Mythical_Man-Month)) that simply adding more developers (especially by ridiculous increases like 10x) nearly always makes development **slower**.

That said, support for things like Trezor is one of the few things that actually could be done by developers not currently engaged in the project.

**Comment by rdlrt** [comment]
social media on github , any reason this "issue" is still open 😄

**Comment by wei3hua2** [comment]
Increasing number of developers doesn't scale linearly. It will simply increases the cost of coordination that, given the nature of software development, can be a huge problem. Also not to forget that lines of code is actually a **cost**. Somebody needs to maintain them. Ironically as it seems, developer actually need to write less code to achieve more, so that it does not build up additional complexity due to maintenance.

Oh hey wait... am i in reddit?

**Comment by erikd** [comment]
Sorry, I meant to close it.
