### ISSUE TITLE
[BUG] - Stale DNS Resolution of Peers

### ISSUE THREAD

**Issue by michaeljfazio** [input-output-hk/cardano-node#2452]
**Internal/External**
*External* 

**Area**
*Other*   Networking / Peer Resolution / DNS

**Summary**
Producers specified in the topology file by DNS are not re-resolved according to TTL settings of the DNS record. It is necessary  to restart cardano-node to force re-resolution of IP addresses.

**Steps to reproduce**
1. Configure relay and block producer to each contain the other as a producer in topology file using a DNS alias.
2. Start both nodes (ensure each node has an established inbound and outbound connection with the other).
3. Stop the block producer node, change its IP address and update the DNS record accordingly.
4. Start the block producer cardano-node instance again.

**Expected behavior**
Relay node should eventually re-establish a connection (outbound) to the block producer. But it does not because it never attempts to re-resolve the block producer IP address (i.e. not respecting TTL setting for DNS record).

**System info (please complete the following information):**
- OS: Ubuntu
- 18.04
- 1.25.1

**Screenshots and attachments**
N/A

**Additional context**

TTL setting on block producer record is default set to 0.
In my case, updating the DNS record when a server is restarted is managed by AWS CloudMap service and is performed automatically as part of HA infrastructure configuration.

------------------ 

What follows is my exact configuration and the behaviour seen:

Three nodes (R1,R2,BP) — relay, relay, block producer.

R1 and R2 have BP in topology
BP has R1 and R2 in topology

All topologies are validated as correct (have not changed since start of Mainnet).

Expectation is that R1 and R2 will have 2 connections with BP (inbound / outbound).

Local IP Addresses:
R1: 10.192.11.38
R2: 10.192.10.125
BP: 10.192.20.198

Results of checking connection status on both relays:

R1
```
> netstat -tan | grep 10.192.20.198
tcp        0      0 10.192.11.38:3001       10.192.20.198:42241     ESTABLISHED
```

R2
```
> netstat -tan | grep 10.192.20.198
tcp        0      0 10.192.10.125:3001      10.192.20.198:45835     ESTABLISHED
tcp        0      0 10.192.10.125:45259     10.192.20.198:3001      ESTABLISHED
```

Note R1 has not formed outbound connection with BP.

A check of R1 logs shows peer suspended (many hours ago):

```
10.192.20.198:38897 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 41> closed when reading data, waiting on next header True"))) 20s 20s
Mar 05 06:42:32 ip-10-192-11-38 cardano[830]: IP 10.192.20.198:42029 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 51> closed when reading data, waiting on next header True"))) 20s 20s
```

No re-connection attempt is logged after peer suspended is witnessed.

**Comment by danbigthink** [comment]
Hi,

This has bitten me more than once. Is there a plan to address this?
I've noticed that the ip addresses are only gathered when the node starts up, there's no worker to eventually replace these. This bug has been open since March.

I'd like to learn more about what system adds DNS records to relays-new.cardano-mainnet.iohk.io, is there any documentation on how this works and which DNS servers are preferred? I usually use googles.

Currently I'm facing a number of these errors on my relay node:
[cardano-:cardano.node.LocalErrorPolicy:Error:145] [2021-12-13 19:25:32.66 UTC] IP LocalAddress "" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 46> closed when reading data, waiting on next header True")

This then causes systems such as the wallet server and dbsync to freak out cause those propogate error messages similar to what happens when you use the cli and query tip, you get:
MuxError (MuxIOException Network.Socket.recvBuf: resource vanished (Connection reset by peer)) "(recv errored)"

Thanks,
Dan

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
