### ISSUE TITLE
[BUG] - Memory Leak

### ISSUE THREAD

**Issue by Fell-x27** [input-output-hk/cardano-node#2978]
**Summary**
A node (and dbsync and cardano-wallet) eats more and more memory day per day. 
Count of tokens is increasing, so ledgerState is growing too. 

After Alonzo release it will become more worse, I guarantee.
It's not a perfect idea to keep in memory the thing which grows every day with no limits. Its a long-distance **memory leak** as a part of software design.

Its not okay when you have to buy enterprise-level servers to run couple cardano applicarions. 

Its not okay when you cannot plan load level.

Its not okay when you have to pay for hardware ten times more than just a year go. 

Its not okay when you think how to run apps on different servers with shared by local netfs socket to buy more time between hardware upgrades.

Its not okay when you know that everything written above its not enough, because RAM utilization grows every day.

RAM is not unlimited. And not cheap when we talk about VPS. 

**You can not ignore this.** 

**Steps to reproduce**
1) Run a node over the mainnet
2) See the "7.5GB" in the htop
3) Run dbsync
4) See the "16GB" in the htop
5) Try to not cry

**Expected behavior**
1) Run a node over the mainnet
2) See the "300M" in the htop
3) Be happy, enjoy your life

**Comment by Xevrac** [comment]
Your prediction may be correct. Since upgrading to 1.29.0 mainnet. I've honestly had a breezy 24hrs. Beyond that. I've noticed two issues creep up.

My relay has now consistently increased in Memory usage over time until it caps at 90% and im worried ill suffer from OOM crashes.

My BP has also begun getting stuck at Syncing 100% every couple hours which is behaviour that has NOT ever occurred before. 

BP 9.2GB RAM, 2GB SWAP, 2GB CACHE

RELAY 10GB, 1GB SWAP

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
