### ISSUE TITLE
CAD-391 Add some logging during startup

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-node#303]
When the node is started there can be a significant delay (eg 5 minutes) before the local socket is created. Apparently the node is validating the immutable DB at this time. It would be nice to add a little logging for this stuff.

**Comment by mrBliss** [comment]
I think it is more likely that the delay is due to the LedgerDB replaying blocks against an older ledger snapshot to bring it up-to-date.

The tracing for the LedgerDB is already in place in `ouroboros-network`: https://github.com/input-output-hk/ouroboros-network/blob/1c320fcb99afd7b077e60a4a0710657c603940ad/ouroboros-consensus/src/Ouroboros/Storage/LedgerDB/OnDisk.hs#L388 This is tracing the ledger replay per block, so the granularity is way too fine-grained.

By default, the ImmutableDB only validates the most recent epoch, which should be fairly quick. In any case, 
it wouldn't hurt to trace the progress of the ImmutableDB. The following trace points can be used:     https://github.com/input-output-hk/ouroboros-network/blob/1c320fcb99afd7b077e60a4a0710657c603940ad/ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Types.hs#L273

**Comment by CodiePP** [comment]
with Serge's latest tracer transformer we can now suppress the logging of repetitive ReplayEvent messages:
```
[nixos19:cardano.node:Info:4] [2019-12-13 17:15:21.31 UTC] {"event":{"snapshot":{"kind":"snapshot"},"kind":"TraceLedgerReplayEvent.ReplayFromSnapshot","tip":"Tip (At (Block {blockPointSlot = SlotNo {unSlotNo = 25811}, blockPointHash = ByronHash {unByronHash = AbstractHash 381d72cc70ea65e242e27d2555010067c02fa5dec92c64f76e4f92102e3edae7}}))"},"kind":"TraceEvent","tip":"genesis(origin)"}
[nixos19:cardano.node.synopsis:Info:4] [2019-12-13 17:15:21.32 UTC] Similar messages elided, 10 total.
[nixos19:cardano.node:Info:4] [2019-12-13 17:15:21.32 UTC] {"event":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":"21600","epoch":"1"},"kind":"TraceEvent","tip":"genesis(origin)"}
```

**Comment by CodiePP** [comment]
PR #445 (elided messages) merged.
