### ISSUE TITLE
[BUG] - cannot spend multi-assets using the `transaction build` command

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#3030]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Native Tokens*    Related to Native Tokens (Mary).

**Summary**

**Steps to reproduce**
1. have an address with multi-assets
2. try to spend 1 utxo with MA

```
cardano-cli query utxo \
    --testnet-magic $MAGIC \
    --address $(cat addr/addr2.addr)

                           TxHash                                 TxIx        Amount
--------------------------------------------------------------------------------------
3b39a05bb7d660003bb8f91293bf649893bdf3972686c00901f68fbe8e2578d9     1        10000000 lovelace + 500 cd9a2da8f3e23457b10a9d573207a6156eedeec43a325fe04727b724.test + TxOutDatumHashNone
5ebf8c1a859d55921013d47e060616ecb5dbe03c2d9995228f107fc79eed0006     1        100000000 lovelace + TxOutDatumHashNone

cardano-cli transaction build \
    --alonzo-era \
    --testnet-magic $MAGIC \
    --tx-in 3b39a05bb7d660003bb8f91293bf649893bdf3972686c00901f68fbe8e2578d9#1 \
    --change-address $(cat addr/addr1.addr) \
    --tx-out "$(cat addr/addr2.addr)+1344798+100 $POLICYID.test" \
    --witness-override 2 \
    --out-file tx2_ma.txbody 

Command failed: transaction build  Error: Non-Ada assets are unbalanced: 8482045 lovelace + 400 cd9a2da8f3e23457b10a9d573207a6156eedeec43a325fe04727b724.test
```

**Expected behavior**
No error on submit. build cmd uses minimum amount of ada as fee.

**System info (please complete the following information):**
- OS Name: Ubuntu
```
$ cardano-cli --version
cardano-cli 1.28.0 - linux-x86_64 - ghc-8.10
git rev 6b9a401f4fa17164856988c9b27dd13c9b47372d

$ cardano-node --version
cardano-node 1.28.0 - linux-x86_64 - ghc-8.10
git rev 6b9a401f4fa17164856988c9b27dd13c9b47372d
```

**Comment by dcoutts** [comment]
We define this as a feature not a bug. The command is deliberately not intended to balance non-ada assets. The error message accurately reflects that.

If you think it's a good idea, file a feature request.

**Comment by Titan-C** [comment]
I feel, I'm missing the feature here.
Why shouldn't the change address balance also balance Non-Ada assets?
change address should take it all.
Also the message is very confusing, because it includes everything that is going into the change, Ada and Non-Ada assets. I fail to understand why they don't balance if they are exactly in the accounted amount for the change address.

By just dropping the amount of lovelaces from the error message, I would more easily infer that Non-Ada assest were not accounted as part of the change output.

Still, by the principle of least surprise, I believe that everything should go to the change address.

**Comment by kieransimkin** [comment]
Yep, I've encountered this too building Artifct.app - very annoying. Why would it balance ADA and not other tokens? That makes no sense to me - either balance everything or balance nothing. Or at least give me a commandline flag to enable non-Ada balancing!

**Comment by kieransimkin** [comment]
By the way, for people looking for a workaround (@qichalerm @jfischoff )- there isn't really a workaround, you just have to balance the transactions - that means every non-Ada token included in an input UTXO must also be included in an output. 
The general theory with all UTXO based blockchains is that every quantity included in every input UTXO must occur in the outputs as well - what goes in must come out. Normally cardano-cli automatically balances these transactions for you, by sending anything unspent Ada to the change address. The feature (bug) described here means that it will fail completely if any of the input UTXOs contain a token which isn't also accounted for in an output. Basically what you have to do, is make sure all tokens in all input UTXOs are also being included in an output, even if that output is to the change address (which is what Cardano-cli should do automatically if you ask me).

**Comment by melchoir55** [comment]
> We define this as a feature not a bug. The command is deliberately not intended to balance non-ada assets. The error message accurately reflects that.
> 
> If you think it's a good idea, file a feature request.

This does not make sense. the `build raw` command is used for building transactions without abstraction. The `build` command (this command) is explicitly for abstracting away change making.

This is clearly a bug.

**Comment by kieransimkin** [comment]
> This is clearly a bug.

Yes, I agree. There is no justifiable reason why the transaction builder would automatically balance ADA but not multi-assets. This is a clear deviation from the expected behaviour - as evidenced by the number of people who have been tripped up by it. 

It'd be really nice if people from IOG could recognise when their design decisions are tripping people up unnecessarily (this isn't the only example) and correct the problem, rather than deny that it exists or argue over semantics.

Clearly there is a problem here - whether it's because the documentation is inadequate, or the behaviour needs to change - something needs to change, otherwise it will continue tripping people up and causing unnecessary confusion.

**Comment by dorin100** [comment]
cc @vfrsilva

**Comment by mateusap1** [comment]
No comment on this? Are there any workarounds? I don't want to have two outputs, one for the change and one for the native assets, adds extra complexity to my code

**Comment by dorin100** [comment]
this is tracked here https://github.com/input-output-hk/cardano-node/issues/3068
