### ISSUE TITLE
[BUG] - cardano-cli transaction build may shortcut script UTxO

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#3059]
**Internal/External**
*External*   otherwise.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**

The impossible happened ...

```
cardano-cli: evaluateTransactionExecutionUnits: the impossible happened: 
RedeemerNotNeeded ScriptWitnessIndexTxIn 1
```

wallet2 wants to unlock some funds from a script and send it to wallet1. To pay for the fees, wallet2 provides an utxo that contains value higher than the value in the script. The script utxo would not be needed to settle the payment. 

Is there a way to force a script utxo to get used?

**Comment by james-iohk** [comment]
This is due to option ordering. The datum/redeemer values must come after the script input else they'll be applied to the wrong input. It's best the cli is not "smart" about this as there can be multiple script inputs etc.
I was actually just coming to raise an issue for this error message, it's not good. We should handle it and say something like "Redeemer value has been applied to an input that doesn't have a script. It is not needed".

**Comment by tdiesler** [comment]
Let me reopen this for review ... the difference in what works and doesn't with various option ordering is subtle.

This seems to generally work, but not always ...

```
  --tx-in $TX_SCRIPT \
  --tx-in-script-file /var/cardano/local/scripts/helloworld5a.plutus \
  --tx-in-redeemer-file /var/cardano/local/scratch/redeemer-secret2.json \
  --tx-in-datum-value 0 \
```

in the case of possible script UTxO shortcut it fails.

This seem to always work ...

```
  --tx-in $TX_SCRIPT \
  --tx-in-datum-value 0 \
  --tx-in-redeemer-file /var/cardano/local/scratch/redeemer-secret2.json \
  --tx-in-script-file /var/cardano/local/scripts/helloworld5a.plutus \
```

It'd probably be better to be unambiguous about the required ordering and not have a dependency on tx-in value, wdyt?

**Comment by james-iohk** [comment]
You need a dependency on `--tx-in` because there can be multiple scripts/datums/redeemers in a single transaction. We did add some clarification in https://github.com/input-output-hk/cardano-node/issues/2858 by improving the help text and format of the nested [] notation in the associated PR, see output of `cardano-cli transaction build --help`.

The following syntax describes `--tx-in` as having optional `--tx-in-script-file` (square brackets mean optional). In practice this means it'll apply the next occurrence (doesn't need to be directly after).
```
(--tx-in TX-IN
  [--tx-in-script-file FILE
    [(--tx-in-datum-file FILE | --tx-in-datum-value JSON VALUE)
      ( --tx-in-redeemer-file FILE
      | --tx-in-redeemer-value JSON VALUE
      )]])
```
The cli options are all handled by [optparse-applicative](https://hackage.haskell.org/package/optparse-applicative), which does a good job of handling this standard interface, but there are some outstanding improvements to be made. We can leave this one open as a proposed improvement but I'd like to clarify expectation.
I get consistent results in your examples above. @tdiesler would you mind providing the entire cmd for each?
