### ISSUE TITLE
[FR] - make `transaction build` to balance automatically also the multi-assets

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node#3068]
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Native Tokens*    Related to Native Tokens (Mary).
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
make `transaction build` to balance automatically also the multi-assets, not only the Lovelace UTXOs

**Comment by kieransimkin** [comment]
I would argue that this is not a feature enhancement, but a bug - I can't find any logical justification for why it would automatically balance ADA but not non-Ada tokens? It just means code that works with UTXOs containing only ADA inexplicably breaks for UTXOs containing non-Ada tokens. Really not expected behaviour at all. If you have left-over tokens of any kind, they should be outputted back to the change address, what is the justification for not doing this?

**Comment by mateusap1** [comment]
Any updates? I think at least adding an option is a good idea

**Comment by dorin100** [comment]
cc @vfrsilva

**Comment by kieransimkin** [comment]
> Any updates? I think at least adding an option is a good idea

Apparently the core dev team at IOG have absolutely no interest in making life easier for us developers, or even explaining the rationale behind their dodgy decisions. This is the 2nd or 3rd ticket I've raised over an silly issue like this which is causing unnecessary confusion and roadblocks to new Cardano developers. Every time I raise an issue, I either get ignored, or I get push back - took months to make any progress on the incompatibility between Serialization-lib and Cardano-CLI transactions - I suspect because dev team bury their heads in the sand. 

Honestly, I like Cardano, I think it's a good system with a good community, and I'm personally very heavily invested it in it, but the process of developing for Cardano is way harder than it needs to be, and IOG needs to pull their fingers out, start listening to your developers, respond to them and try to make the platform easier to develop on - Cardano will lose to other cryptos if this doesn't happen, that is already happening. 

Why develop for a platform that's harder than others, written in a language nobody knows (Haskell) and with a core development team who seem to have no interest in making life easier for their development community?

**Comment by larestrepo** [comment]
I just hit this issue, is there any workaround? change-address should handle the balance to both ADA and non-ADA assets.

**Comment by jterrier84** [comment]
Same problem here. Any final solution or workaround available?

**Comment by marijanp** [comment]
What errors are you all getting and what version of cardano-node/-cli are you using? For me the balancing of non-Ada values works.

**Comment by jterrier84** [comment]
I get this error: 
Command failed: transaction build  Error: Non-Ada assets are unbalanced: 1354601 lovelace + 5000000000 afc910d7a306d20c12903979d4935ae4307241d03245743548e76783.4153484942 + 1 f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a.6d696e6931706f6f6c

My cardano-cli version:
cardano-cli 1.34.1 - linux-aarch64 - ghc-8.10

**Comment by larestrepo** [comment]
cardano-cli 1.34.1 - linux-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23

This is what I found: the change-address works if you spend all the assets from the utxo. Now if you want to partial spend (say you have 30 and want to send 10 to another address), change address is not able to figure out that the remaining 20 must be sent to the change address specified in the tx.

**Comment by kieransimkin** [comment]
> cardano-cli 1.34.1 - linux-x86_64 - ghc-8.10 git rev [73f9a74](https://github.com/input-output-hk/cardano-node/commit/73f9a746362695dc2cb63ba757fbcabb81733d23)
> 
> This is what I found: the change-address works if you spend all the assets from the utxo. Now if you want to partial spend (say you have 30 and want to send 10 to another address), change address is not able to figure out that the remaining 20 must be sent to the change address specified in the tx.

Yes, this is quite clearly a bug, I'm not sure why so much resistance to fixing it.

**Comment by MatthewTristan** [comment]
How can we get more attention from IOG about this?

**Comment by dorin100** [comment]
cc @CarlosLopezDeLara , @kevinhammond

**Comment by manupadillaph** [comment]
Some news about this?

**Comment by MatthewTristan** [comment]
Any new news?

**Comment by kieransimkin** [comment]
Recommend you go on Twitter and tag everyone with IOHK or IOG in their handle on a daily basis. 

Generally I think everyone is now using serialisation-lib for transaction generation now, although that's a world of pain in itself. So.. have fun 🙄🤦‍♂️

**Comment by Ftrain27** [comment]
Any updates on this? Currently going through an EMURGO Plutus cohort where we're working with multiple assets. I agree with kieransimkin, I definitely expected --change-address to work with multiple assets, especially since there are very little technical differences between lovelace and all other native assets. Seems like a bug worth fixing.
