### ISSUE TITLE
[BUG] - cardano-node on Mainnet already consumes 7,15 GB of RAM and growing

### ISSUE THREAD

**Issue by danielmain** [input-output-hk/cardano-node#3260]
**Internal/External**
*Internal*

**Summary**
cardano-node needs today (28/10/2021) on my MacBook 7,17GB RAM, last week was 6GB

**Steps to reproduce**
1. Open Daedalus Wallet 4.3.1 (Mainnet)
2. Wait until sync is done

**System info (please complete the following information):**
- OS Name: Mac OS Big Sur
- Node version 1.29.0

**Screenshots and attachments**
<img width="903" alt="image" src="https://user-images.githubusercontent.com/4303099/135113427-b772aa30-5ab0-453d-88e1-052d7fb6e6b9.png">
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/4303099/135114070-2832ee3d-b3c8-47b1-b937-6115ee4e7c45.png">

**Additional context**
This number seems to be growing.

**Comment by soyfrien** [comment]
1.31.0 recommends 12 GB RAM minumum. Perhaps consider a lightweight wallet like Yaroi. I believe you can still vote in Catalyst with it. So you're not losing much besides whatever your Mac is lending to the network.

**Comment by d0n13** [comment]
If you restart the node once it has synced it tends to use a lot less

**Comment by soyfrien** [comment]
On my nodes they prefer to be stopped rather than restarted. Restarting them maxes out the CPU, not doing much with memory or IOs.

**Comment by d0n13** [comment]
Yea, it has to validate the existing blocks when it restarts and seems to be doing nothing in the logs but the CPU maxes out one thread. This maybe could be improved with multi-threading but it is what it is.
My node just died there too. Seems like 8GB of ram is not enough. I have more ordered. Recommended is 12GB so I guess I'l let the VM to have 16Gb and hope it stabilises. 
So sorry if my answer is misleading but it was running for ages with low memory until it got something big to do and died due to lack of memory. I only have the node running a few days as I'm starting to learn Haskal so I'm a bit green still.

**Comment by soyfrien** [comment]
Oh, wait my relays are only 8 GB. Damn...

I'm gonna stripe four SSDs and make a swap file there.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
