### ISSUE TITLE
[BUG] - cardano-node may report invalid git rev

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-node#3440]
**Internal/External**
*External*   otherwise.

**Area**
*Build*   

**Summary**

When I build the node like this

```
git clone -b 1.32.1 https://github.com/input-output-hk/cardano-node.git $wrsrc
cd $wrsrc

echo "Cabal update ..."
cabal update

echo "Cabal configure ..."
cabal configure

echo "package cardano-crypto-praos" >> cabal.project.local
echo "  flags: -external-libsodium-vrf" >> cabal.project.local

echo "Cabal build all ..."
cabal build all
```

I see the correct git rev `4f65fb9a` for HEAD. However, the resulting binary reports ...

```
cardano-node 1.32.1 - linux-x86_64 - ghc-8.10
git rev e9de7a2cf70796f6ff26eac9f9540184ded0e4e6
```

which seem to be the git rev for https://github.com/input-output-hk/cardano-config instead of cardano-node

In previous versions the above used to work and the binaries contained the correct git rev

**Comment by rdlrt** [comment]
The issue has been around for months (almost since STN pre-mainnet), while there were supposedly fixes - I am not sure if they got reverted or never made it.
Previously we used to have [this line](https://github.com/cardano-community/guild-operators/blob/06d6fad49e3e7e3081877f2df46505c75da5a29d/scripts/cnode-helper-scripts/cabal-build-all.sh#L7) in `cabal-build-all.sh` to get around the issue (as building config takes only few seconds), but ye - would be nice to get it fixed

**Comment by tdiesler** [comment]
I don't have a cached version of cardano-config. It seems whatever I do, it builds this thing and (incorrectly) gets the git rev from it.

**Comment by erikd** [comment]
This has been fixed in `db-sync` thanks to @tmcgilchrist . Maybe he can fix it here too.

**Comment by Cz1975** [comment]
I had a same problem. The problem was with the version of the cabal. cabal 3.2.0.0 caused the same git rev, after the install cabal 3.4.0.0 the git rev is correct.
It helped me:
https://forum.cardano.org/t/cabal-3-4-0-0-not-changing-from-3-2-0-0-solved/56957

**Comment by tmcgilchrist** [comment]
Working on a fix for this. @erikd

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
