### ISSUE TITLE
[BUG] - Cardano Block producer Uptime never exceeds 48 hours

### ISSUE THREAD

**Issue by chirkunov** [input-output-hk/cardano-node#3462]
**Internal/External**
External

**Area**
Other   

**Summary**
The block producer uptime resets every 18-48 hours. Could be the node restarting or the server crashing. Block producer has 16GB of RAM. Have seen this behavior ever since I run the stake pool. Cardano relay nodes do not show this problem.

**System info (please complete the following information):**
Ubuntu 20.04.3 LTS
Cardano node version: 1.32.1

**Comment by orpheus-antpool** [comment]
Check the logs of the node. It will display useful information that will help you figure out why your node is crashing. Without a clear error message or triggers for the crash, a bug report on GitHub will not receive too much attention. The best place to discuss this issue is the Cardano Forum: https://forum.cardano.org/c/staking-delegation/operators-talk/119.
