### ISSUE TITLE
Question about --testnet-magic in cardano-cli

### ISSUE THREAD

**Issue by bjing** [input-output-hk/cardano-node#3554]
Hi, 

I've got a two questions:

1. Is there a reason why we always have to specify `--testnet-magic` when using cardano-cli? Why can't it just default to the official testnet that this points to: https://explorer.cardano-testnet.iohkdev.io/en?

2. Whatever the reason, I'm thinking we can default to the official testnet and still allow users to specify `--testnet-magic` if they want to point to something else, right?

**Comment by newhoggy** [comment]
Hi @bjing,

My understanding is we always supply a `--testnet-magic` is because the official testnet is just one of many testnets and accidentally connecting to the wrong testnet is often a source of confusion and the flag exists to make it obvious that this has happened.  It is for this reason we make the flag mandatory.

Does this answer your question?

**Comment by bjing** [comment]
Thanks @newhoggy, but what are the other testnets used for? If there's an official testnet, why not default to that? From a user point of view, I don't get the `a source of confusion` part.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
