### ISSUE TITLE
[FR] - Implement the ability to calculate the previous epoch's leadership schedule

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#3555]
Implement the ability to calculate the previous epoch's leadership schedule.

**Comment by Jimbo4350** [comment]
This is not currently possible without caching the previous epoch nonce. It's also not strictly necessary as SPOs can simply store the output of the current leadership schedule calculation and reference it if necessary in the future.

**Comment by dorin100** [comment]
Andrew is providing also the "previous" option [here](https://github.com/AndrewWestberg/cncli/blob/develop/USAGE.md#calculate-leaderlog)

**Comment by Jimbo4350** [comment]
@dorin100 
>prev and current logs are available **as long as you have a synchronized database**. 

Yes, I see he has it. However this requires caching previous epoch nonces and therefore the user has to store additional information in order to do this.

What is the typical use case for previous leadership schedules? Are users generally interested in the most recent one?

**Comment by dorin100** [comment]
> Yes, I see he has it. However this requires caching previous epoch nonces and therefore the user has to store additional information in order to do this.

Couldn't we use the details that we already have in the ledger state about the previous epoch? I think we already have details about 3 epochs (prev, current, next) in the ledger state now.

>What is the typical use case for previous leadership schedules? 
I think the most useful use case would be when debugging missing blocks - like my pool has 10 blocks assigned in epoch X, now in epoch X+1 (after X ended) I am looking at the performance of the pool in epoch X and I see I missed 3 blocks and the first thing I would want to check is what happened with those 3 blocks. 

In order to debug something like this, it would be useful to use the same source of truth - the CLI in this case, and I would do that like interrogating the CLI in order to tell me what were the blocks allocated to my pool in the previous epoch. 

Anyway, the leadership scheduled can be saved in each epoch and then used as required. The "previous" option is more like nice to have if it is simple to be implemented.
