### ISSUE TITLE
bench: passive P2P enabled, ledger peers

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-node#4028]
@coot told us this is like #4027, but needs a >0 value for `useLedgerAfterSlot`:
```
EnableP2P: True
TestEnableDevelopmentNetworkProtocols: True
useLedgerAfterSlot: 1
```

This also, of course, needs the peers to be in the ledger state (so we need bake them into genesis).

**Comment by deepfire** [comment]
https://github.com/input-output-hk/cardano-node/issues/4028 is a prerequisite.

**Comment by deepfire** [comment]
https://github.com/input-output-hk/cardano-node/pull/4234 enables ledger peer injection.

**Comment by coot** [comment]
I'm actually not sure if using ledger peer in benchmarking is a good idea.  It will increase uncertainty, and more randomness into the benchmarks.  The nodes are making random decision who to promote to hot peers, churn, once an hour, removes 20% of least performing peers. Since you're executing this in a controlled environment (one data centre, right?) it will just add more randomness.  Different benchmarks will not be comparable as they will use different topology, and it will be even harder to decide whether the new results are better or worse than previous ones.

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.
