### ISSUE TITLE
[BUG] - min required UTxO reported by CLI is not correct

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node#4061]
*Internal*

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
In Babbage, both `transaction build` and `transaction calculate-min-required-utxo` report 857690 Lovelace to be minimum required UTxO for Lovelace-only output with no datum. However I am able to create UTxO with just 849070 Lovelace (using `transaction build-raw`).

**Expected behavior**
CLI reports precise minimum required UTxO.

**System info:**
- OS Name: Fedora 35
- Node version: 1.35.0-rc3

**Comment by gitmachtl** [comment]
Is this on vasil-dev? doing my own calculation with the method used in alonzo-era i get 999920 lovelaces. using the cli inbuilt calculation method i get 961130 lovelaces. wondering where the 849070 are coming from. using also node 1.35.0-rc3.

**Comment by gitmachtl** [comment]
Now that the transaction calculate-min-required-utxo this is a bit strange, because how to query the real minimum value with this function? In the past i used --tx-out ADDRESS+0 because of the word boundary it didn't make a difference in the outcome and the result was the minUTXO that must be used. But now that the calculation is done down to the bytelevel, the result of a minUTXO request depends on the amount you're doing the request for. Thats strange. Examples:

**Comment by JaredCorduan** [comment]
The build command might be overestimating the size needed, perhaps using `maxBound` somewhere.

The min value depends (linearly) on the number of bytes of the output. You cannot therefore figure it out precisely by substituting zero for the value you want. See this CIP: https://github.com/cardano-foundation/CIPs/pull/265/files

**Comment by gitmachtl** [comment]
> But I guess the suggestion is for the CLI to take an output with zero ada, and compute the fix point?

Yes exactly, like its now working in the alonzo-era. Otherwise external tools would need to do at least two or three requests with different lovelaces values to get the amount that really works for sending it out with that value.

**Comment by Jimbo4350** [comment]
> In Babbage, both transaction build and transaction calculate-min-required-utxo report 857690 Lovelace to be minimum required UTxO for Lovelace-only output with no datum. However I am able to create UTxO with just 849070 Lovelace (using transaction build-raw).

So this is complaining about the change output. We purposely overestimate the size of the change output because we want to avoid recursively solving for the tx fee (i.e evaluate tx fee, put fee in tx, evaluate the fee again, put the fee in the body etc). This is expected.

**Comment by Jimbo4350** [comment]
> The transaction calculate-min-required-utxo is a bit strange, because
@gitmachtl can we move this to a new issue? @mkoura if you are satisfied with the above answer can we  close this issue?

**Comment by CarlosLopezDeLara** [comment]
Removing from 1.35.1.  As @Jimbo4350 mentioned, current behavior is  intended and expected.

**Comment by lehins** [comment]
@Jimbo4350 we now have a function `setMinCoinTxOut` in `cardano-ledger-api` (which is a new packahge tha twe started that will provide all the useful functionality for downstream users of ledger).

That function will calculate the true minimum lovelace for any `TxOut` in any era precisely by finding the fixpoint:

https://github.com/input-output-hk/cardano-ledger/blob/1176affe9b2a7a3b50c1ceda00cc92f237ea6360/libs/cardano-ledger-api/src/Cardano/Ledger/Api/Tx/Out.hs#L32-L40

@CarlosLopezDeLara You maybe want to consider reopening this ticket, since now it will be very easy to adopt this in cardano-node thus minimize the amount
