### ISSUE TITLE
🌎 Better Open Source | Architecture decisions records (ADRs)

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4329]
## What
Decisions we make should be properly recorded for future reference and to validate assumptions or expected results. 

- [x] Discuss/Select the format to use. 
- [x] Create "decisions" folder on `cardano-node` repo. 
- [x] Upload template and guidelines to GH.  

## Why 
As we move to a more open source project,  decisions should be understood by a wider range of parties. Having a record of key decisions allows for future assumptions and expected results validation. 

## Persona:Benefits

- Architects and cardano developers: Learn why a particular decision was made, context, status, consequences/trade-offs, expected results, etc. Have information for future decisions.  

## Dependencies
Agreement between parties.

**Comment by CarlosLopezDeLara** [comment]
https://github.com/input-output-hk/cardano-node/wiki/Architecture-Decision-Records

**Comment by abailly-iohk** [comment]
@CarlosLopezDeLara I am glad the node is moving to ADRs. As the Head of Architecture for Cardano I would have been interested in being involved in that process. Also, it seems to me these ADRs should not be in the wiki but part of the code as they should be created in sync with the code they apply to, so that looking at the codebase timeline one can see when an ADR was put in effect and what his consequences were.
