### ISSUE TITLE
Make sure `wallet` is built on CI

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#436]

**Comment by mark-stopka** [comment]
Do you want to transition to GiHub Actions like Jormungandr did? I might pick this up then, but I a, not planning to learn the current CI =). Anyway, until recently there was no way to disable cardano-wallet build, that was added with #597, and by default was designed to keep the current workflow which would attempt to build `cardano-wallet` so build should fail before you even check for existence of `executables`. 

Otherwise I believe it's easiest to check it in `mainnet.sh` that the `executable` exists, I can submit that PR as well.

**Comment by Jimbo4350** [comment]
the example wallet no longer lives in `cardano-node`
