### ISSUE TITLE
[BUG] - growing block production delay on epoch switch (ep360-362) 

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/cardano-node#4421]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
During the last two epoch transitions (361, 362), the period without new blocks has increased significantly again.

**Expected behavior**
no extraordinary long delay between new blocks  

**System info (please complete the following information):**
seen on all kind of systems and setups. relays, block producers, node version 1.35.3 and 1.34.1

**Screenshots and attachments**

ep359>360
<img width="636" alt="2022-09-08_09h02_40" src="https://user-images.githubusercontent.com/13198220/189058450-9e64b03d-bf77-4084-9ab6-5eccc0263653.png">
<img width="638" alt="2022-09-08_09h17_49" src="https://user-images.githubusercontent.com/13198220/189059463-c9240f5d-5857-47b9-9a77-14a191ba4a79.png">

ep360>361
<img width="641" alt="2022-09-08_09h04_15" src="https://user-images.githubusercontent.com/13198220/189058478-722e6caf-965e-4b02-8472-9f60e134e9c8.png">
<img width="629" alt="2022-09-08_09h18_28" src="https://user-images.githubusercontent.com/13198220/189059572-60a3bbba-cb5a-4480-ad9f-b722f4adc2cd.png">

ep361>362
<img width="636" alt="2022-09-08_09h05_05" src="https://user-images.githubusercontent.com/13198220/189058514-29bd2876-aa09-4745-87d2-dd47bfed6620.png">
<img width="628" alt="2022-09-08_09h18_57" src="https://user-images.githubusercontent.com/13198220/189059665-b9f1477e-82fa-4e07-a441-0b64c8dd826c.png">

**Additional context**
on all 3 epoch transitions one relay node ran on 1.34.1 and all other blockheight lines come from 1.35.3 nodes.
CPU graph below each epoch transition is from one relay node

**Comment by zandeck** [comment]
You can see it on the explorer as well

![image](https://user-images.githubusercontent.com/3318114/189073887-b675aa54-cb28-4a71-8b19-8af9fd74b028.jpeg)

![image](https://user-images.githubusercontent.com/3318114/189075019-2b5b58e5-1d2b-4bda-870d-f3fdbdf38901.png)

**Comment by gufmar** [comment]
by looking at v6 vs v7 blocks produced in the epochs we see

ep359 60% v7   no extraordinary delay towards ep360
ep360 88% v7   5 minutes of delay towards ep361
ep361 94% v7   12 minutes of delay towards ep362

**Comment by njd42** [comment]
It happens that the team are all together today.

We've had a detailed look at the logs so as to understand whether this was due to a change (eg. due to software version) or an emergent interaction between the higher cpu load that occurs at the start of the epoch and the leadership schedule (basically a "height battle between nodes that are under temporary processing strain").

Our conclusion is that, from those logs (and the other evidence) that it was the latter.

![Epoch 360/361 boundary](https://user-images.githubusercontent.com/28633284/189111855-a24e3126-444c-4fe6-b504-d2b67e41396e.png)

As can can be seen in the block 7728110 the system is diffusing and adopting blocks in its usual time range. The diffusion/adoption time of block 7728109 was around 40s indicative of the extra cpu cost not just of performing the epoch boundary crossing but that the diffusion of such a block was slowed (blocks are only forwarded after having being adopted)

There was more than one candidate for block 7728108 - they were created 16s apart; node logs indicate other blocks (as would be expected) that were not forwarded as they were not better "candidates" for the chain extension (by the normal resolution rules)

Yes, 12 minutes is long, but 5-6 min for the first block adopted in an epoch is not that unusual. We don't see this as a bug. 

We have already scheduled a meeting to review the situation at the next epoch boundary to double check our conclusion here. 

It should be noted that this is does not represent any risk to the integrity of chain growth

**Comment by rdlrt** [comment]
@njd42 If there's a follow-up meeting to discuss / review / confirm the above explanation , prolly best to keep this open and not close?

**Comment by papacarp** [comment]
@njd42 I expanded the details in realtime view a bit for more context.  Perhaps this will be useful for your follow up meeting or for next epoch.
![image](https://user-images.githubusercontent.com/11194546/189128057-fed9788b-60ac-4a76-9d98-66f0233dc418.png)
1.  Its important to note that in the height battle, the CFLOW block was only reported by 1 node and actually that node was CFLOW.  So it wasn't really a height battle, the CFLOW block never made it anywhere.  
2. The BASHO block was made at slot 674, but the first report of it was 29 seconds later with median prop time of 52 seconds.  The full story is in the prop histogram for that block:  
![image](https://user-images.githubusercontent.com/11194546/189139924-f479b653-d6ce-42a3-862d-67e3441d2e38.png)
So under the "heavy load" hypothesis, this may demonstrate when the nodes were coming online after the epoch switch and starting to process blocks again.  note that **this means epoch processing takes at minimum 674+29=703 seconds with the bulk of the nodes done by 674+100=774 seconds after epoch switch**.  So a little over 1 minute of variability between nodes and over 11 minutes on average.
3.  The follow on AZUR3 block is in slot 742 but had a very interesting prop delay chart with almost all nodes reporting it at the same time at 742+40=780 seconds after epoch switch.
![image](https://user-images.githubusercontent.com/11194546/189141157-5276ba1b-e810-4d54-ae5b-190caba2e3d7.png)
I guess the hypothesis here is that AZUR3 was also finishing epoch processing and produced the block late and it then got distributed quickly since everyone was ready.  Might be good to have a look at AZUR3 logs to see what time they actually produced their block.

**Comment by gufmar** [comment]
By looking into number of established tcp connection at that ep switch time I would have expected some small decline, caused by remote p2p logic dropping and re-establishing connections.
Instead I noted on all my public relays a significant spike in tcp connections starting at 21:45utc 

![Screenshot_2022-09-08-16-00-01-79_e589e2e5eef7246e2b9e3e77d02e4167](https://user-images.githubusercontent.com/13198220/189157913-eb0a1272-9e7e-4921-abf1-587021716e8d.jpg)


If of interest I can provide more detailed views

**Comment by cloudstake** [comment]
> @njd42 I expanded the details in realtime view a bit for more context. Perhaps this will be useful for your follow up meeting or for next epoch. ![image](https://user-images.githubusercontent.com/11194546/189128057-fed9788b-60ac-4a76-9d98-66f0233dc418.png)
> 
> 1. Its important to note that in the height battle, the CFLOW block was only reported by 1 node and actually that node was CFLOW.  So it wasn't really a height battle, the CFLOW block never made it anywhere.
> 2. The BASHO block was made at slot 674, but the first report of it was 29 seconds later with median prop time of 52 seconds.  The full story is in the prop histogram for that block:
>    ![image](https://user-images.githubusercontent.com/11194546/189139924-f479b653-d6ce-42a3-862d-67e3441d2e38.png)
>    So under the "heavy load" hypothesis, this may demonstrate when the nodes were coming online after the epoch switch and starting to process blocks again.  note that **this means epoch processing takes at minimum 674+29=703 seconds with the bulk of the nodes done by 674+100=774 seconds after epoch switch**.  So a little over 1 minute of variability between nodes and over 11 minutes on average.
> 3. The follow on AZUR3 block is in slot 742 but had a very interesting prop delay chart with almost all nodes reporting it at the same time at 742+40=780 seconds after epoch switch.
>    ![image](https://user-images.githubusercontent.com/11194546/189141157-5276ba1b-e810-4d54-ae5b-190caba2e3d7.png)
>    I guess the hypothesis here is that AZUR3 was also finishing epoch processing and produced the block late and it then got distributed quickly since everyone was ready.  Might be good to have a look at AZUR3 logs to see what time they actually produced their block.

AZUR3 produced the block at 2022-09-07T21:57:13.03Z
[block71021542.txt](https://github.com/input-output-hk/cardano-node/files/9528269/block71021542.txt)

**Comment by Straightpool** [comment]
> So you produced your block on time, but for whatever reason we had a rollback and then your block was re-applied at 2022-09-07T21:57:53.15Z which corresponds exactly to when everyone else applied your block as well. The "ExceededTimeLimit" and resulting "ErrorPolicySuspendConsumer" seems to cause problems.

I agree. One of my relays even "blacked" out for a minute 

![image](https://user-images.githubusercontent.com/42584250/189177907-d84e1445-3e67-40c8-a568-3cf4d1be578f.png)

When this relay was incapable of reporting metrics CPU was at max
![image](https://user-images.githubusercontent.com/42584250/189178173-d187f1d3-2a49-4c14-a256-2045b1fae0cf.png)

Different view 
![image](https://user-images.githubusercontent.com/42584250/189180215-c8dd0980-0403-4e5d-b048-da860fa67100.png)

In comparison this is 2 epochs prior on 28th of August also on 1.35.3:
![image](https://user-images.githubusercontent.com/42584250/189181054-3028bc04-6ac4-44e1-be3d-be74f3e0b329.png)

In the logfiles the relay never crashed but the log is completely saturated with messages like these pretty much for the duration of the blackout

{"app":[],"at":"2022-09-07T21:59:15.26Z","data":{"address":"<censored>","event":"ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError (MuxIOException Network.Socket.recvBuf: resource vanished (Connection reset by peer)) \"....
{"app":[],"at":"2022-09-07T21:58:57.97Z","data":{"kind":"PeersFetch","peers":[{"declined":"FetchDeclineChainNotPlausible","kind":"FetchDecision declined","peer":{"local":{"addr"...
{"app":[],"at":"2022-09-07T21:58:57.05Z","data":{"domain":"\"<censored>\"","event":"Failed to start all required subscriptions","kind":"SubscriptionTrace"},"env":"1.35.3:950c4","....
{"app":[],"at":"2022-09-07T21:58:50.77Z","data":{"address":"<censored>","event":"ErrorPolicySuspendConsumer (Just (ApplicationExceptionTrace ExceededTimeLimit (Handshake) (ServerAgency TokConfirm))) 20s","kind":"ErrorPolicyTrace"},"env":"1.35...

**Comment by StakeWithPride** [comment]
This is still an issue today. 8m27s epoch boundary pause.

**Comment by 3DMintLab** [comment]
> This is still an issue today. 8m27s epoch boundary pause.
I had a lot of DNSErrors in my relay log during the switch to 363. Could this be related to the long pause? 
[2022-09-11 20:47:27.71 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.133.43.175:3001 ExceededTimeLimit

**Comment by disassembler** [comment]
This is a ledger task that we are working on. we've benchmarked some things https://github.com/input-output-hk/cardano-ledger/pulls?q=is%3Apr+is%3Aclosed+author%3ATimSheard and thanks to Frisby have a great new plan https://github.com/input-output-hk/cardano-ledger/pull/3141

The reason for closing this was it doesn't pertain directly to the node code base and we're trying to clean up issues at the moment.

**Comment by disassembler** [comment]
Also see https://github.com/input-output-hk/cardano-ledger/issues/3132#issuecomment-1317364564
