### ISSUE TITLE
[Question] Is it possible to set reward generation rate in privatenet stake pool?

### ISSUE THREAD

**Issue by EV6999** [input-output-hk/cardano-node#4425]
Hello, I am trying to find how to set reward generation rate in privatenet stake pool to shorten the rewards generation time for testing.
It seems there is no config item for reward rate.

Thanks.

**Comment by ltouro** [comment]
Not expert, but my two cents: Reward is a function of fees expended by users plus monetary expansion rate minus the cut that goes to treasury. So I guess you should tune treasury_growth_rate and monetary_expand_rate protocol parameters. 

Or just hammer alot of transactions with excess fees (also known as tipping)

**Comment by CarlosLopezDeLara** [comment]
@EV6999  Rewards are distributed at the epoch transition,  _"Rewards to both the pool operators and the pool members will be calculated and distributed by the system some time after the end of an epoch."_

So you can shorten epoch length on your network so that you see rewards come more frequently.  
 
For additional details see section 5 of https://hydra.iohk.io/build/17427421/download/1/delegation_design_spec.pdf
