### ISSUE TITLE
Problems upgrading Cardano Node from 1.35.2 to 1.35.3

### ISSUE THREAD

**Issue by abdellahaski** [input-output-hk/cardano-node#4427]
**External**

**Area**
Cardano node upgrade from 1.35.2 to 1.35.3

**Summary**
I'm trying to upgrade my Cardano node from 1.35.2 to 1.35.3 using the [stakepool247 guide.](https://cardano-node-installation.stakepool247.eu/cardano-node-upgrades/upgrade-to-1.35.0#2.-upgrading-and-updating-the-system-packages)

**Steps to reproduce**
Same steps on the guide untill the `cabal build all` command which return the following error (after running for a while ofc):

`cabal: Failed to build exe:trace-dispatcher-examples from
trace-dispatcher-1.29.0.
`

**Expected behavior**
Build complete

**System info :**
- OS Name: Ubuntu
- OS Version: 22.04.1 LTS

**Screenshots and attachments**
The full logs : https://gist.github.com/abdellahaski/94637b5a6c043047bdb09fe3d4989b1c

**Additional context**
I already upgraded using this same method many times before without any hiccups and everything went smoothly.

**Comment by CarlosLopezDeLara** [comment]
Instructions to build from source are found here: https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md I just tested these build instrucitons from above and the process works as expected. 

If you are following docs from [stakepool247 guide.](https://cardano-node-installation.stakepool247.eu/cardano-node-upgrades/upgrade-to-1.35.0#2.-upgrading-and-updating-the-system-packages) please raise the issue with them since it is out of our control.
