### ISSUE TITLE
[BUG] - Withdrawl.md missing: 401

### ISSUE THREAD

**Issue by russch** [input-output-hk/cardano-node#4758]
**External*

**Area**
*Other*   

**Summary**
The withdraw rewards markup doc referenced at https://iohk.zendesk.com/hc/en-us/articles/4407568373657-Withdraw-pool-rewards is missing. Hitting the link returns a 404

1. Navigate to https://github.com/input-output-hk/cardano-node/blob/master/doc/stake-pool-operations/withdraw-rewards.md per the FAQ

Expect: A markup doc
Result: 404

**Comment by MarcFontaine** [comment]
The information that you are looking for is probably here:
https://github.com/input-output-hk/cardano-node/blob/master/doc/stake-pool-operations/11_withdraw-rewards.md
I'm closing this issue, because a stale link into the `cardano-node` repository is not a really a bug.
Thanks for reporting it anyway.
@CarlosLopezDeLara can you maybe update the docs at https://iohk.zendesk.com that contain the stale link ?
