### ISSUE TITLE
Cross-platform clean shutdown

### ISSUE THREAD

**Issue by rvl** [input-output-hk/cardano-node#726]
Provide a method which [cardano-launcher](https://github.com/input-output-hk/cardano-launcher) can use to politely request that `cardano-node` exits.

If `cardano-node` is killed impolitely (with SIGKILL on POSIX or TerminateProcess on Windows), it will do a complete revalidation of the chain on the next startup. This can take some minutes.

See [cardano-launcher/docs/windows-clean-shutdown.md](https://github.com/input-output-hk/cardano-launcher/blob/master/docs/windows-clean-shutdown.md) for a discussion of the issue and suggested solution.

This is the implementation in cardano-wallet - [withShutdownHandler](https://github.com/input-output-hk/cardano-wallet/blob/ab979c8ebd683a6a8c8bc234b9b9084d9e467836/lib/launcher/src/Cardano/Startup.hs#L89-L130). This code is enabled when the `--shutdown-handler` switch is provided to the `cardano-wallet` CLI.

**Comment by mrBliss** [comment]
> If `cardano-node` is killed impolitely (with SIGKILL on POSIX or TerminateProcess on Windows), it will do a complete revalidation of the chain on the next startup. This can take some minutes.

Correct. But why are you killing with `SIGKILL`? Just use `SIGTERM` (which should be the default, `SIGKILL` should only be tried when `SIGTERM` doesn't work) no revalidation is needed.

**Comment by rvl** [comment]
Windows -- check the linked doc.

**Comment by mrBliss** [comment]
> Windows -- check the linked doc.

I see. Windows :roll_eyes:

**Comment by dcoutts** [comment]
@rvl can you try `GenerateConsoleCtrlEvent` with either the ctc+c or break events? This may require that the launcher put the node into it's own process group, as mentioned in the MSDN docs.

https://docs.microsoft.com/en-us/windows/console/generateconsolectrlevent

This is the closest I can find to a standard method on Windows. It only works for console applications, but the node and wallet are console so that's ok.

I know that the wallet takes the approach of terminating when stdin is closed, but this isn't standard behaviour on Windows except for console applications that actually use stdin. It is also not something you want to do uniformly on other platforms: process monitors like systemd will by default connect their stdin to `/dev/null` so the "block until stdin is closed" trick will immediately fail.

**Comment by rvl** [comment]
@dcoutts Thanks for investigating.

1. I do not know how to call `GenerateConsoleCtrlEvent` from nodejs. I can try to look into it. But even if it is possible, it wouldn't be as easy as closing a file.

2. This method will not help in the case where Daedalus crashes or is killed. There would have been no chance to send ctrl-c, so the `cardano-node.exe` process will stay running. On the other hand, if it's trying to read stdin, an exception will be thrown and cardano-node knows that it should exit. I added a [test case for this in cardano-launcher](https://github.com/input-output-hk/cardano-launcher/blob/master/test/cli.test.ts) because I think this feature is essential.

3. I totally agree that it is not something you would want to do uniformly on other platforms, and that it won't work with systemd. That's why in `cardano-wallet` the clean shutdown handler is only enabled when the `--shutdown-handler` command-line switch is provided. You can do the same in `cardano-node`.

**Comment by dcoutts** [comment]
2. that's true.

3. Perhaps we can do it with a specific pipe FD passed in. `--shutdown-ipc FD`. I don't like overloading `stdin` for this.

**Comment by rvl** [comment]
`--shutdown-ipc FD` would be fine. `FD` will be a number, e.g. 3, right?
