### ISSUE TITLE
Test vectors for use by Emurgo

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#797]
Sebastian (Emurgo) has asked us to produce test vectors for

o   bech32 addresses generated from keys
o   examples of signed transactions (different kinds of inputs, certificates, etc.)

These could presumably come from test cases for the node CLI (or maybe the wallet)

**Comment by KtorZ** [comment]
How is that one closed :thinking:  ?

**Comment by KtorZ** [comment]
We have test vectors for addresses here: https://gist.github.com/KtorZ/b2e4e1459425a46df51c023fda9609c8

Although it's using blake2b_224 for internal hashing while cardano-node is still using blake2b_256, so these vectors are so-to-speak incompatible with cardano-node at the moment. 

For transactions, I haven't seen any? The Adrestia team is working on some, although we are also limited by what cardano-cli is capable of and, to what's _currently_ implemented in cardano-node. Since the primary audience for these vectors is 3rd parties, I am somewhat reluctant in giving them vectors that we'll have to invalidate in a few weeks when the final crypto is adopted in the node (in particular regarding addresses, which is the only discreprancy I am aware of).
