### ISSUE TITLE
stake distribution CLI command

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-node#979]
As a pool operator, I would like to know what the current stake distribution is to identify how many blocks I anticipate I should make in a given epoch. Having the entire ledger state as a snapshot dumped to json would get me this and many other things, but if it's easier to do stake distribution, that would be a good first step.

**Comment by erikd** [comment]
This one is a bit tricky. The part in the CLI is relatively easy, but this will almost certainly need additions to the node-to-client protocol between the node and the CLI.

**Comment by kevinhammond** [comment]
I will pursue this with Sam to work out what is actually needed.  We may be able to get the necessary information in another way, or it may be quickest to simply implement the full ledger state rather than splitting out (as in Erik's ticket).  We're using "priority high" to mean absolutely essential for the MVP (we cannot run without it) - "highest" would mean that the system cannot continue at all, so this is "priority medium".
